### ISSUE TITLE
Undo takes time to load data

### ISSUE THREAD

**Issue by Dooleylabs** [SBPrime/AsyncWorldEdit-Premium#100]
# There's no error to report, but with version 3.4.1, our server has been experiencing a severe increase in the time it takes to load undo data, while redo, cut, and paste all run normally. I think something may be bugged in the latest optimizations to the operation. I've tried wiping all AsyncWorldEdit config data / undo data and have tried it across multiple servers. The results are the same.

I'll be using version 3.4.0 until it's fixed. Still the best plugin for large worldedits and worth the money!

AsyncWorldEdit: 3.4.1
WorldEdit: 6.1.4 | 3596-b9801eb

**Comment by SBPrime** [comment]
This MIGHT be due to the fixes in the loader. There was a bug that caused the undo to load incorrectly. In the new version I decided to rewrite the undo load/save and it should be 10-100 times faster.

Fixed in version: 3.4.2 (I know you need to wait for the official release :P)

**Comment by Dooleylabs** [comment]
Version 3.4.2 is showing the same behavior as 3.4.1. I've reset the config and tried a few tweaks, but undos are still taking several minutes to load. The server has 12GB of RAM maximum and uses less than 1G regularly.

Is there something I could do to the config to fix this? These undos are usually under 1 million blocks, so I'd not expect it to take so long.

Still love this plugin!

AWE: 3.4.2
WE: 6.1.4 | 3621-2e10fe8

**Comment by SBPrime** [comment]
1, Starting from v3.4.2 undos are executed directly from undo file. The older versiions required a full load of the files before any blocks ware placed.
2. In v3.4.2 I optimized the undo load speed. According to my tests the load speed went down from ~400ms to ~50ms for 1M undo entries.
3. You can always disable undo disk storage in AWE config
4. What operations do you do maybe this is not a undo thing but something related to block placer?
5. Could you check the IO operations? Maybe this is a problem with the read/write?
6. How large are the undo files?
7. Did you do a check using smaller edits?
8. Try the DirectChunk API operations for changing blocks (for example /chunk set)

**Comment by Dooleylabs** [comment]
Apparently the server wasn't allocating more memory for worldedits, and one of our dev's wanted to see how the server would run at 720MB minimum, 10G maximum. Other than terrible worldediting, everything runs well. I've adjusted the minimum RAM back to 2GB. It seems better now.

**Comment by SBPrime** [comment]
Ok, please keep me updated. For now I'll assume that this  was a configuration issue.
