### ISSUE TITLE
Asynchronous world loading

### ISSUE THREAD

**Issue by FarisR99** [SBPrime/AsyncWorldEdit-Premium#103]
Hey, is there a way to asynchronously load a world via. AsyncWorldEdit? I know FastAsyncWorldedit has this feature, but I'd rather stick to a plugin I already use.

**Comment by SBPrime** [comment]
AsyncWorldEdit does not support async world loading and as far as I know you can't do a fully async world loader using bukkit. As far as I know the fawe implements a some sort of a wrapper that allows you to edit the blocks asynchronously. I might be mistaken I don't know that plugin that well. 

Never the less if you explain what exactly do you need/want I'll look into this if its possible to add to AWE or I'll suggest other solution.

**Comment by FarisR99** [comment]
Thanks for the quick reply. I am making a minigames plugin that cycles through maps, and every time a new map is chosen, the old maps world is unloaded, the folder is deleted, and the map is copied and loaded again. I want to do this asynchronously. I know a solution is schematics but its longer to create maps as I would have to select the whole map region, create a schematic, load it into a world at position 0,100,0 and then set the locations in the config like Team 1 Spawn etc. It's fine though, I'll just use FastAsyncWorldEdit for the minigames server only, and the rest of the servers'll use AWE.

**Comment by SBPrime** [comment]
Like I said I don't think that asynchronous chunk loading is possible (fawe loads chunk synchronously that I'm surer of). I would suggest looking at the WorldEdit restore commands and or AsyncWorldEdit chunk API. It allows you to change chunks in practically async way (only the actual flush is done in sync).

**Comment by FarisR99** [comment]
Thing is, the thing I'm regenerating is an actual building (e.g. arena). Is there a way I can 'capture' all the blocks- Wait, maybe if I, onEnable() just load all maps, create a schematic from them then use that instead, I could probably just paste the schematic. Is there a tutorial on how to copy and paste schematics via. AWE?

**Comment by FarisR99** [comment]
Re-opened just incase you're not getting notifications (and technically I still have an 'issue' related to this).

**Comment by SBPrime** [comment]
You can check here: 
https://github.com/SBPrime/AsyncWorldEdit-Premium/wiki/API

This is old and might be outdated but its a good place to start. I don't have time to do a proper tutorial.

If you are going to use the DirectChunk API I would suggest that you check the API javadoc and or API source code (https://github.com/SBPrime/AsyncWorldEdit-API). For the DIrect Chunk ting I would suggest looking at:  [IDirectChunkCommands.java](https://github.com/SBPrime/AsyncWorldEdit-API/blob/master/src/org/primesoft/asyncworldedit/api/directChunk/https://github.com/SBPrime/AsyncWorldEdit-API/blob/master/src/org/primesoft/asyncworldedit/api/directChunk/IDirectChunkCommands.java)  createPaste and then use the IBlocksPlacer to invoke the job. If you have questions don't hesitate to ask.

**Comment by FarisR99** [comment]
Ah, there's no API information on creating schematics and storing it into an object (not file, I wanted to create a schematic from a cuboid region in each minigame map and just store it, pasting it every time a new game starts) nor pasting a schematic stored (only from player edit sessions which I can't use, I need methods which don't require players). Thanks anyway, I'll just stick to FAWE.
