### ISSUE TITLE
Cannot remove undo files

### ISSUE THREAD

**Issue by manuelgu** [SBPrime/AsyncWorldEdit-Premium#104]
Upon disconnect or worldedit commands, the following error message is being sent
`[AsyncWorldEdit] Error removing file plugins/AsyncWorldEdit/undo/5212412e-71cf-47fe-b58e-39475038760b/5c5e8c8f-322a-4b38-a739-0e9f11295333.1`
`[AsyncWorldEdit] Error removing file plugins/AsyncWorldEdit/undo/5212412e-71cf-47fe-b58e-39475038760b/5c5e8c8f-322a-4b38-a739-0e9f11295333.1.idx`

**Comment by SBPrime** [comment]
Fixed in 3.4.3
