### ISSUE TITLE
AsyncWorldEdit still ignores the WorldEdit blacklist.

### ISSUE THREAD

**Issue by totemo** [SBPrime/AsyncWorldEdit-Premium#108]
I have read through @SBPrime's suggestions in #97 and tried many variations on the settings in config.yml, including completely removing the `disallowedBlocks` setting in all groups, and various permutations of the `disallowedBlocksUsage.patterns` and `disallowedBlocksUsage.blockSet` flags.

I have tested these settings in AWE 3.4.2 and 3.4.4. The former, according to #97, should work at the very least. But none of these settings configures AsyncWorldEdit to use WorldEdit's blacklist.txt. Please detail the value of all settings in AWE (and BlocksHub, if applicable) that must be set for AWE to use the per-world blacklist.txt we have configured in WorldEdit.

Thank you.

**Comment by totemo** [comment]
Apparently I'm confusing WorldEdit's disallowed blocks with WorldGuard's blacklist here. Sorry, disregard.

**Comment by SBPrime** [comment]
For WorldGuard black list to work you need to install the BlocksHub plugin and configure AWE to use it.
