### ISSUE TITLE
ProgressBar does not work (TitleManager)

### ISSUE THREAD

**Issue by Toshka17** [SBPrime/AsyncWorldEdit-Premium#110]
http://pastebin.com/9GXcs5pj

**Comment by SBPrime** [comment]
You are using a mismatched version of the AWE core and the progress display plugins.
1. Stop server
2. Go to /plugins/AsyncWorldEdit
3. Remove Plugins directory and "installed" file
4. Start server
5. Enable TitleManager progress bar plugin
6. Restart server

**Comment by Toshka17** [comment]
I did everything that you have written, took a new plugin AsyncWorldEdit-TitleManager.jar replaced him. But Progressbar still does not work. No errors.

**Comment by SBPrime** [comment]
Send me the full startup log.

**Comment by Toshka17** [comment]
http://pastebin.com/q9UDECri

**Comment by SBPrime** [comment]
1. Where did you put the AsyncWorldEdit-TitleManager?
2. Send me the AWE config file.

**Comment by Toshka17** [comment]
1. amm.. server/plugins/
   2.http://pastebin.com/kuAaKTkY

**Comment by SBPrime** [comment]
You can't put the AsyncWorldEdit-TitleManager.jar into the plugins directory. You need to keep it in the /plugins/AsyncWorldEdit/plugins directory. The bridge needs to be initialized in a special way by AWE.
