### ISSUE TITLE
Shadowing issues when pasting

### ISSUE THREAD

**Issue by Killertom63** [SBPrime/AsyncWorldEdit-Premium#111]
When pasting large objects, the shadows break. See screenshots.

Placing a block to update the lighting fixes it, but we have a lot of broken areas because of that. 

http://imgur.com/a/ju7Vo

**Comment by SBPrime** [comment]
1. I assume that you are using chunk paste not a regular paste
2. use chunk relight (after selecting a cuboid) to relight chunks.

**Comment by Killertom63** [comment]
What's the command for that please @SBPrime

**Comment by SBPrime** [comment]
`/chunk relight`

**Comment by SBPrime** [comment]
Any update?

**Comment by Killertom63** [comment]
Yeah that works, is there a way so that we don't have to do that every time?

**Comment by SBPrime** [comment]
What command did you use in the first place?

**Comment by Killertom63** [comment]
//schematic load <name>
//paste -a

That's it.

**Comment by SBPrime** [comment]
If its simple paste then its not an AWE bug (If you had used /chunk paste then it would be AWEs fault). Please check if you don't have fast mode enabled or something like that.

**Comment by Killertom63** [comment]
Doing /chunk reload doesn't even work by the way. It just says Done, and doesn't update anything

**Comment by Killertom63** [comment]
And we're not using //fast. We never use it for anything. Server has 20Gb of Ram.

**Comment by Killertom63** [comment]
/chunk paste actually makes the lighting worse.

**Comment by SBPrime** [comment]
1.I never said anything about chunk reload (I don't think that this has ever worked for me on pure WE), I mentioned chunk relight
2. Chunk paste resets the light to 0 and after that it queues blocks for relight (it will take some time before the relight is finished)
3. When you do regular paste AWE does not touch the light. All the light is calculated by spigot.

**Comment by Killertom63** [comment]
Sorry I meant /chunk relight. Was tired when I wrote that message. 

After waiting for chunk paste to finish (10 sec paste) waited 30mins for the blocks to relight. Nothing happened.

**Comment by SBPrime** [comment]
1. Send the AWE config
2. If the vanilla (spigot) relighter does not wotk the chunk relight also won't work because it uses the same algorithm.

**Comment by Killertom63** [comment]
http://pastebin.com/AfzveFRz

I've got 20Gb of free RAM on that server.

**Comment by SBPrime** [comment]
Like I said if, the vanilla block light fails then there is nothing that I can do. 
Ram has nothing to do with this.

**Comment by Postremus** [comment]
I can also confirm, that lighting seems to be incorrect after a "/chunk paste". "/chunk relight" does not seem to do anything.
I will look deeper into this issue, since it also affects my server.

**Comment by SBPrime** [comment]
In version 3.4.8 I added support for sky light it should solve lighting issues when using chunk paste, chunk relight.

You can also try the chunk relight -v This forces relight of the selection using the native minecraft light algorithm.

It would also help if you could provide the schematic (if it's private you can send it using spigot pm).
