### ISSUE TITLE
Items from blocks exploding when moving in stages

### ISSUE THREAD

**Issue by andrewgazelka** [SBPrime/AsyncWorldEdit-Premium#116]
**AsyncWorldEdit version 3.4.6**

If I have a block with items in it (ex: Dispenser or chest) and there is redstone next to it and the redstone is moving to the same location the block with items currently is in, the block with items will release all of its items. 

If I //move in the direction of the arrow and then undo this would occur.

![image](https://cloud.githubusercontent.com/assets/7644264/20855139/b22e53c0-b8bf-11e6-9c89-19065a832f88.png)

**Comment by SBPrime** [comment]
This is not a AWE bug. Using old version of WE (without AWE) causes this problem when updating to latest WE removes the problem. 

What version of WE are you using?
