### ISSUE TITLE
place blocks using AWE API?

### ISSUE THREAD

**Issue by Porama6400** [SBPrime/AsyncWorldEdit-Premium#118]
How can I queue and place block with AsyncWorldEdit API?
(not from schematic)

**Comment by SBPrime** [comment]
All dipends how many blocks you want to place. If its a couple of blocks at a time I would use: IBlocksPlacer.PerformAsAsyncJob and simply set blocks on the passed edit session. Please look at the API here: https://github.com/SBPrime/AsyncWorldEdit-api/

**Comment by Porama6400** [comment]
So I should create session with IAsyncEditSessionFactory.java?
how can i get World?

**Comment by SBPrime** [comment]
Check the WorldEdit API on how to create an edit session. Things that you need to do differenlty:
1. After obtaining the EditSessionFactory cast it to IAsyncEditSessionFactory
2. Create the thread safe edit session
