### ISSUE TITLE
chunk relight doesn't work?

### ISSUE THREAD

**Issue by Porama6400** [SBPrime/AsyncWorldEdit-Premium#120]
chunk relight seem to not working.

when use /chunk set
then use /chunk relight

But it's still bright under block I set

**Comment by SBPrime** [comment]
1. Please provide the AWE config
2. The light calculation sometimes takes time (after chunk commands)
3. The chunk relight works ONLY for selected area
4. You can always try /chunk relight -v

**Comment by Porama6400** [comment]
I used default configuration

I set 50x50x50 stone
I use /chunk set then i use /chunk relight , wait until it says relight is finish

near the surface , lighting is looking good , but when i dig down deeper , everything seem to have light level at 15

EDIT: Sorry for my bad English skills

**Comment by SBPrime** [comment]
OK got it now. 

1. Does the error appear after relogin? (sometimes its only a client light issue)
2. Does chunk relight help (either one -v or regular) when you select entire chunk
3. Are you able to provide a 100% full proof scenario for reproduction?

**Comment by Porama6400** [comment]
Well , actually -v do very well
Here's my test : https://youtu.be/p6gPikBFH80

**Comment by SBPrime** [comment]
Ok, I'll check it.

**Comment by SBPrime** [comment]
Fixed in 3.4.8
