### ISSUE TITLE
Crash and //copy

### ISSUE THREAD

**Issue by Sanyasp** [SBPrime/AsyncWorldEdit-Premium#127]
https://hastebin.com/yuwelikoma.md

**Comment by SBPrime** [comment]
Without the full crash log I'm unable to help.

**Comment by Malachiel87** [comment]
I got the same issue, there there, my server crashed after a //copy command.
https://pastebin.com/kmiL9czk
and the crash report:
https://pastebin.com/Q55YCcfk
Running AWE 3.4.10, WE 6.1.5 and 1.8.8

**Comment by SBPrime** [comment]
What version of spigot are you using?

**Comment by Malachiel87** [comment]
I am using 1.8.8 spigot + viaversion (for allow client 18-1.12 to connect)
