### ISSUE TITLE
1.12 Error while Command

### ISSUE THREAD

**Issue by Tiippex** [SBPrime/AsyncWorldEdit-Premium#135]
https://pastebin.com/Ynd8cTpG

**Comment by SBPrime** [comment]
1. Do all undoos fail or only this one?
2. What OK?

**Comment by Tiippex** [comment]
1. It is sometimes, i guess something like 60%. They didnt fail. Only this error appears.
2. Which OK?

**Comment by SBPrime** [comment]
Sorry I meant to write what OS :D

**Comment by Tiippex** [comment]
Spigot 1.12
Java 8
Debian 8
virtual Server (2Cores / 8GB Ram/ SSD)

That enough information?

**Comment by SBPrime** [comment]
Ok. Did something "special" happen before the error occurred? What operation did you try to undo?

**Comment by Tiippex** [comment]
Nothing Special, it was Copy Paste.

**Comment by SBPrime** [comment]
Did the server timeout, crash? did the player log-out?

**Comment by Tiippex** [comment]
no nothing

**Comment by ryans1230** [comment]
I've been seeing the same issue. As far as I'm aware, its just normal W/E commands, however can't create the undo for some reason (even though other players have undos just fine)

**Comment by Tiippex** [comment]
@SBPrime any solution? i still get this error sometimes...

**Comment by SBPrime** [comment]
I did some tests, unfortunately I was unable to reproduce the error. I'm planing to rewrite the undo mechanics in the next version.

**Comment by SBPrime** [comment]
Fixed.
