### ISSUE TITLE
Get an error when pasting with API

### ISSUE THREAD

**Issue by caxerx** [SBPrime/AsyncWorldEdit-Premium#137]
I have working an plugin use AWE API, But when I performing an paste task. Sometimes It spam this error:
https://pastebin.com/T8P0PwiA

And here is my code:
https://github.com/caxerx/DynamicDungeon/blob/master/src/me/blackphreak/dynamicdungeon/MapBuilding/oBuilder.java

**Comment by caxerx** [comment]
anyone? bump

**Comment by SBPrime** [comment]
What version of the server are you using?

**Comment by caxerx** [comment]
1.12 PaperSpigot #1139

**Comment by SBPrime** [comment]
Unfortunately I do not target paperspigot. I tried to fix this error but unfortunately paper has some changes that break my chunk unload/load detection.

**Comment by caxerx** [comment]
Ok, I will try to use the original Spigot
