### ISSUE TITLE
//paste bug

### ISSUE THREAD

**Issue by coco0325** [SBPrime/AsyncWorldEdit-Premium#141]
There's a bug on paste.

14.02 19:29:26 [Server] WARN [AsyncWorldEdit] Task #8 for AsyncWorldEdit v3.4.11 generated an exception
14.02 19:29:26 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.TileEntity.a(Lnet/minecraft/server/v1_12_R1/NBTTagCompound;)V
14.02 19:29:26 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.readTagIntoTileEntity(Spigot_v1_12_R1.java:116) ~[?:?]
14.02 19:29:26 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.setBlock(Spigot_v1_12_R1.java:253) ~[?:?]
14.02 19:29:26 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:416) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:305) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:296) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.blockPlacer.entries.WorldFuncEntryEx.process(WorldFuncEntryEx.java:79) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:446) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:373) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:84) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:263) ~[?:?]
14.02 19:29:26 [Server] INFO at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:79) ~[?:?]
14.02 19:29:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
14.02 19:29:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
14.02 19:29:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
14.02 19:29:26 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
14.02 19:29:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
14.02 19:29:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]

**Comment by SBPrime** [comment]
You are using an outdated version of WorldEdit.
