### ISSUE TITLE
Unable to check latest plugin version

### ISSUE THREAD

**Issue by stevmei** [SBPrime/AsyncWorldEdit-Premium#142]
Hello,

Is it just me receiving this message? Seems that the version check fails?

Running version: AsyncWorldEdit version 3.4.11

I will be grateful if you can send me this information.

**Comment by SBPrime** [comment]
Send the console output.

**Comment by stevmei** [comment]
Console on startup:
https://pastebin.com/Pd2aq5nS

No output when logging in, just a chat message for me:
https://imgur.com/a/6VQhw

Server:
This server is running Paper version git-Paper-1310 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by SBPrime** [comment]
Fixed in version 3.5
