### ISSUE TITLE
Ability to execute block of code when schematic paste job is finished?

### ISSUE THREAD

**Issue by UltraGameCoder** [SBPrime/AsyncWorldEdit-Premium#143]
I can't find a way to check if my schematic paste is finished.
I want to teleport the player to the schematic when it's finished placing all the blocks.
Is there currently a way I can achieve this? (I also need to call some other functions beside the player teleportation )

**Comment by SBPrime** [comment]
You can do this by starting a job from the blocksplacer. You also need to use the blocksplacer to track if your job has finished. Please check the IBlocksPlacer for further information.

**Comment by UltraGameCoder** [comment]
@SBPrime I can't seem to figure it out.
May you want to look at my code and tell me how you would implement it in the load function?
```JAVA
public void loadIsland() throws FileNotFoundException, IOException, MaxChangedBlocksException {
		String schematicName = getPlayer().getUniqueId().toString();
		AtomicBoolean isNew = new AtomicBoolean(false);
		File file = PlayerStatsManager.getManager().getPlayerIsland(schematicName, isNew);
		
		org.bukkit.util.Vector originVector = center.toVector();
        Vector to;
        if (isNew.get()) {
        	to = new Vector(originVector.getBlockX() - 21,60,originVector.getBlockZ() -21);//to = new Vector(originVector.getBlockX(),originVector.getBlockY(),originVector.getBlockZ());
        	Vector borderCenter = new Vector(to.getX(),to.getY()+2,to.getZ());
        	generateBorder(borderCenter,21);
        }else {
        	to = new Vector(originVector.getBlockX() - 21,60,originVector.getBlockZ() -21);
        }
        World weWorld = new BukkitWorld(center.getWorld());
        WorldData worldData = weWorld.getWorldData();	
        FileInputStream input = new FileInputStream(file);
        ClipboardReader reader = ClipboardFormat.SCHEMATIC.getReader(input);
        Clipboard clipboard = reader.read(worldData);
        input.close();
        Extent source = clipboard;
        Extent destination = WorldEdit.getInstance().getEditSessionFactory().getEditSession(weWorld, -1);
        ForwardExtentCopy copy = new ForwardExtentCopy(source, clipboard.getRegion(), clipboard.getOrigin(), destination, to);
        copy.setSourceMask(new ExistingBlockMask(clipboard));
        Operations.completeLegacy(copy);
	}
```
Source: https://github.com/PublicGameCoder/Survival-Islands/blob/master/Survival-Islands/src/main/java/islands/PlayerIsland.java

I've wanted to return some kind of object/id to check from if the schematic paste is finished.

**Comment by SBPrime** [comment]
1. Cast the edit session factory to [IAsyncEditSessionFactory](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/worldedit/IAsyncEditSessionFactory.java)
2. Get an instance of [IBlockPlacer](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/blockPlacer/IBlockPlacer.java) and [IPlayerManager](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/playerManager/IPlayerManager.java) from the AWE plugin
3. Using  the [IPlayerManager](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/playerManager/IPlayerManager.java) get an instance of [IPlayerEntry](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/playerManager/IPlayerEntry.java)
4. Use the [getThreadSafeEditSession](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/worldedit/IAsyncEditSessionFactory.java#L65-L73) to create the edit session.
5. Use the [performAsAsyncJob](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/blockPlacer/IBlockPlacer.java#L137-L146) to paste the schematic (as lambda method or sub class), please make sure that you used the same [IPlayerEntry](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/playerManager/IPlayerEntry.java)

To listen for jobs take a look at:
[addListener](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/blockPlacer/IBlockPlacer.java#L71) and [addStateChangedListener](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-API/src/main/java/org/primesoft/asyncworldedit/api/blockPlacer/entries/IJobEntry.java#L58). The first listener needs to be added once when you enable the plugin, the second one needs to be added and removed when you get an event from the IBlockPlacer.

**Comment by UltraGameCoder** [comment]
Thank you! first I didn't know all the things you've meant but no I've figured it out.
Thanks for helping!

**Comment by SBPrime** [comment]
Your welcome.
