### ISSUE TITLE
Add a configuration option to disable the cleanup messages

### ISSUE THREAD

**Issue by guidodobboletta** [SBPrime/AsyncWorldEdit-Premium#144]
It would be nice to have a configuration option to disable the cleanup messages such as this:

```
[19:27:44 INFO]: [AsyncWorldEdit] Undo cleanup started...
[19:27:44 INFO]: [AsyncWorldEdit] ...undo cleanup done.
```

As they can get in the way of looking at the console output.

**Comment by UltraGameCoder** [comment]
Yea, it would be nice to have that. and also the same concept for the paste messages.

**Comment by SBPrime** [comment]
Done (currently in master).
