### ISSUE TITLE
Error when preforming a task

### ISSUE THREAD

**Issue by pat-p** [SBPrime/AsyncWorldEdit-Premium#145]
ASyncWorldEdit: v3.5.2
WorldEdit: v6.1.9-SNAPSHOT;3736-f67f2ed
PaperSpigot: 1.12.10-R0.1-SNAPSHOT (d43da9f)

ASyncWorldEdit Start-up Log: https://paste.ee/p/FDvnh
WorldEdit Start-up Log: https://paste.ee/p/qHASG
ASyncWorldEdit Config: https://paste.ee/p/MHg6d (Default)

When doing an action such as //set or //copy, etc, i get an error thrown that is provided below. It then proceeds remove blocks at a very slow speed. The server has more than enough memory. Could you please provide any insight on this issue?

Error: https://paste.ee/p/0DFIB

**Comment by SBPrime** [comment]
1. You did not provide spigot login,
2. The paste is not an error its a debug dump

**Comment by pat-p** [comment]
If you’re asking for my spigot username it’s MasDaddy. 

As for the issue, we have the default config which to my knowledge should run at a great speed no problem. Tried tweaking settings and such. With debug on that dump happens when doing any action. Then the speed goes very slow. Never does it complain about ram either.

Any ideas? Let me know if you need any more info.

**Comment by SBPrime** [comment]
1. If you enable the debug mode it will slow down
2. Speed might vary depending on the operation. For example if you do edits over void or high in the air (edits that cause light update) will be much slower then regular ones.

Please also provide the amount of free ram and the current config that you are using.

**Comment by pat-p** [comment]
I'm not sure which exact ram you're asking for so I will provide all.
64GB on the box itself. 
32GB allotted spigot instance for the server.
And according to /gc in Essentials, we have ~15GB free.

The config can be found here; https://paste.ee/p/5SfA4 Pretty sure it's the default config as well.

The size of the operation doesn't seem to matter with my issues though, it can be a big 50k blocks count or a 100 block count and it will just chug at times and be very slow. We only turned on the debug initially after seeing these issues with hope to get some sort of insight.

**Comment by SBPrime** [comment]
Speed optimization was done in 3.6.0
