### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by Halfhand1** [SBPrime/AsyncWorldEdit-Premium#148]
I have been getting this startup error recently. Not sure where it came from since everything was working perfectly a while back.

I am using asyncworldedit premium

https://pastebin.com/07Ue5ZHK

**Comment by SBPrime** [comment]
You are using a mismatched version of WorldEdit, please go to AWE plugin page on spigot and check the supported version of WorldEdit. Install the proper version on the server and perform a full restart.
