### ISSUE TITLE
Add support for WE dev build.

### ISSUE THREAD

**Issue by MrSpock78** [SBPrime/AsyncWorldEdit-Premium#152]
WE: 7.0.0-SNAPSHOT;3996-871541d
WG: 7.0.0-SNAPSHOT;1780-b48e145
AWE: AsyncWorldEdit-3.6.0-rc-03
Paper:  git-Paper-488 (MC: 1.13.2)

https://pastebin.com/384acRPt
The set is executed and performing with WE/AWE but the above exception is shown in console.

**Comment by SBPrime** [comment]
Any reason why are you using snapshots? I currently switched to supporting releases from https://dev.bukkit.org/projects/worldedit/files

**Comment by MrSpock78** [comment]
I´m always using latest dev-builds as they are recommended and are fixing other bugs.
It is not a production server and changes in dev-builds will go into beta anyway.

> Welcome to the WorldEdit Channel! If you have a question, ask it. If you have an error, please *pastebin* your server log. Download: http://builds.enginehub.org/job/worldedit

**Comment by SBPrime** [comment]
The dev builds will get into releases but since I need to tie directly to WE I cant rely on those. The changes might break from one dev build to another. Supporting multiple dev builds is in some cases (your is one of those) not possible. I also can't force my users to constantly update to latest dev builds. They might need other plugins that are not updated to dev builds, only releases.

**Comment by MrSpock78** [comment]
I totally understand, there is almost every day a new build and many things are changing. I´m still testing around with different builds to find a stable solution for my production server when I will update to 1.13.2.
No hurry, keep up the good work 👍

**Comment by TheRootAdmin** [comment]
Even with the beta build and your latest beta build the issue still exists though.

**Comment by SBPrime** [comment]
@TheRootAdmin You would need to provide a full startup log. I tested the rc04 on beta4 without any problems.

**Comment by SBPrime** [comment]
Done in RC-05
