### ISSUE TITLE
Compatibility with PlotSquared in 1.13

### ISSUE THREAD

**Issue by jewome62** [SBPrime/AsyncWorldEdit-Premium#154]
Hello,

I want to know before buy the plugin in premium, if AsyncWorldEdit work with PlotSquared and WE plot restriction.

I know i use combination in past (in minecraft1.11 server) of AsyncWorldEdit and PlotSquared but i'm not sure of compatibility with current pre-release version

The only information i have, is Plotsquared work well with WorldEdit7.0 beta 4

So if you can confirm that.

Thanks

**Comment by SBPrime** [comment]
Last time I checked PlotSquered was not yet updated to support WorldEdit 7. You should check with teh plot squered team.

Bottom line is if it works without AWE then it should work with AWE.

**Comment by jewome62** [comment]
Thanks for your answer.
I have buy the plugin, i wait you accept transaction and i will try It
