### ISSUE TITLE
Physicswatch always listening

### ISSUE THREAD

**Issue by Postremus** [SBPrime/AsyncWorldEdit-Premium#16]
Hey,

Why is the physicswatch always listining for the blockphysicsevent? Shouldn't it be enough to just listen for it while pasting?
It is causing small amounts of lag. This is the situation on a test server, with only me online.
http://puu.sh/kEoxp/7c5933ada0.png

greetings
Postremus

**Comment by SBPrime** [comment]
This is the easiest and most reliable solution. If you wanted to start the PW task you would need to check it EVERY time you add blocks to the queue, and stop it when its empty, Secondly if you look closely to the timings each entry is ~1.05ms (1 tick = 50ms).

If this was only a question, I hope that I answered it. If you have any arguments why it should be changed send please tell me.

**Comment by Postremus** [comment]
Hey,

sorry for not being clear in what i want in the first place.

In a more real life like test case, the load goes up to 10%:
http://puu.sh/kG7mX/26b41c5452.png

I actually want this behaviour to be changed in AWE.
Either should awe automaticly disable the listener, or it should have an api, which allows me to disable the listening completly.

**Comment by SBPrime** [comment]
I noticed that you want it changed :P I asked because in my opinion its not an issue when its running on idle mode. The 2'nd screen shot is for idle or when placing blocks?

Never the less I'll try to squeeze this into next release.

**Comment by Postremus** [comment]
In the second screeen shot, it was in idle. nothing was done with worldedit while the timings run.
I created a lot of block updates from the pasted schematic, which caused the physicsevents.
thank you!

**Comment by SBPrime** [comment]
I did some refactoring of the physics watcher. It should use up much less ticks from now, as long as its "empty" (no blocks are being watched). I decided to not disable it when the queue is empty and then re-enable it when blocks are queued because this would require loads of reflection.

**Comment by Postremus** [comment]
I did some timings yesterday, and can confirm that your refactorings improved the situation quite a lot.
before: http://timings.aikar.co/?url=14511424
after: http://timings.aikar.co/?url=14511480
thank you!

**Comment by SBPrime** [comment]
Your welcome. If you need anything let me know. 

Ps. Its 3.47ms vs 0.62ms looks great ;)
