### ISSUE TITLE
P2 World edit restriction not process

### ISSUE THREAD

**Issue by jewome62** [SBPrime/AsyncWorldEdit-Premium#160]
Hello.

### Version
Spigot : git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
AsyncWorldEdit-Premium : v3.6.0-rc-04
WorldEdit: v7.0.0-beta-04;17f52cb
PlotSquared: 4.88

### Explain
A no-allowed player can make commande on road as //pos1, //pos2 and //set stone without limitation. or //stack
With worldedit only, there are no problem.

No error into log.

But ! The undo and redo are restricted ! So if stack from my plot to road, that's print over the road.
And if i undo, that's remove only block into my plot.
same with //redo

I have limitation to not enable into AWE if less 100 blocs. But i try same with 100000 block and same thing.
//set and //stack in my exemple do not restrict on restricted area, but //undo and //redo apply restriction.

My available if you want try settings.
Thanks

**Comment by SBPrime** [comment]
Pleas add versions of the plugins (WE, AWE, P2).

**Comment by jewome62** [comment]
Hello @SBPrime,
My first paragraph don't take you enought informations ?

AsyncWorldEdit-Premium : v3.6.0-rc-04 (from spigot AWE-Premium, so i dont show link because it's private)
WorldEdit: v7.0.0-beta-04;17f52cb https://dev.bukkit.org/projects/worldedit/files/2646337/download
PlotSquared: 4.88 : https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.88.jar

**Comment by SBPrime** [comment]
Sorry I somehow scrolled to the explanation and missed the versions. Its all that I need.

**Comment by jewome62** [comment]
I know my explanations are so exciting that you want to read me.
I should write novels ^^

**Comment by SBPrime** [comment]
Fixed in rc04b
