### ISSUE TITLE
//Copy and //paste signs does not work

### ISSUE THREAD

**Issue by AngieC233** [SBPrime/AsyncWorldEdit-Premium#162]
Using:
AsyncWorldEdit - Premium 3.6.0-rc-04b
CraftBukkit version git-Spigot-f56e2e7-07e504c (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Worldedit Bukkit-Official (7.0.0-beta-04)

Can't seem to copy/paste signs.... It would not paste signs when signs are //copy but the rest of the blocks are fine  
Have this spamming in the console if it helps to identify the issue...
https://pastebin.com/Fht1xj5f

**Comment by SBPrime** [comment]
This is caused by WE not supporting spigot 1.13.2. You need dev build.
