### ISSUE TITLE
Where to get 1.13 build?

### ISSUE THREAD

**Issue by MrBuzzzz** [SBPrime/AsyncWorldEdit-Premium#164]
I bought the premium version today but cannot see where the 1.13 build is. I don't mind its in Alpha but where is it?

**Comment by SBPrime** [comment]
The jars are available only at spigot. All details about the transactions can be found on the plugin description page. Ill quote 2 of them:
* transactions are accepted and processed manually,
* only payments from verified paypal accounts are accepted, transactions from unverified or unregistered will be rejected and refunded.

Please contact me directly on spigot.

SB.
