### ISSUE TITLE
CoreProtect Inspector Cannot Find User Data

### ISSUE THREAD

**Issue by hamcoremusic** [SBPrime/AsyncWorldEdit-Premium#171]
I just updated to the latest versions of AWE, BlocksHub, and CoreProtect as of March 16.

I wanted to test the CoreProtect intergration, so I placed a cuboid of stone and used `/co inspect`. Upon clicking the AWE placed block, it said there is not user data. I have enabled block logging on all configs. Should the WorldEdit logger in the CoreProtect config be turned off?

**Comment by SBPrime** [comment]
You would need to send me the startup log + AWE, CoreProtect config + logs from the AWE operation.

**Comment by SBPrime** [comment]
No update closing the issue.
