### ISSUE TITLE
Java 12

### ISSUE THREAD

**Issue by BuildingDave** [SBPrime/AsyncWorldEdit-Premium#174]
Hey, I just updated our Linux VMs to the latest Java 12 Version and it seems that AsyncWorldEdit can‘t generate the Injectore because of this. Do you plan to Update AsyncWorldEdit build towards Java 12 or would you mind to send me a Java 12 compiled Version? 
I use AWE-Premium.

Thanks in advance
BuildingDave

**Comment by SBPrime** [comment]
1. The plugin was desdigned with Java 8 in mind and changes in to reflection in Java 9+ break it without special commandline parameters. Therefore if you are updating from 8 this might be the problem.
2. There is and most likelly won't be a dedicated Java 12 version of the plugin
3. You should provide the full error log (probably the full server startup log) without this I dont know whats failing it might be my code it might be the support library that I use.

**Comment by SBPrime** [comment]
Closing this because the same error was reported here:
https://github.com/SBPrime/AsyncWorldEdit/issues/223
