### ISSUE TITLE
AWE randomly hangs server 

### ISSUE THREAD

**Issue by Bloodrayne1995** [SBPrime/AsyncWorldEdit-Premium#176]
Hi,

yesterday we updated our plugins and server to the latest version. And now AsyncWorldEdit randomly hangs server longer than 15 seconds.

LogFile: [https://pastebin.com/pWQP1Uip](https://pastebin.com/pWQP1Uip)
ServerVersion: current 1.13.2 (Build 626) ; previous Build 566
Plugins we have updated:
- AsyncWorldEdit (3.6.0 RC 05 ==> 3.6.0 RC 06)
- Worldguard (7.0.0 beta 3 ==> 7.0.0 RC 1)
- Worldedit (7.0.0 beta 5 ==> 7.0.0 RC 2)

We restore temporaly to previous versions of these plugins.

We hope you can help us there.
If you need any informations, just ask us and we try to gather these informations.

Greetings
Bloodrayne

- 

-

**Comment by SBPrime** [comment]
Please update to 3.6.0, that should fix the problem. Because of some inner changes in WE AWE did not cache the set operation and it was not running async.

**Comment by Bloodrayne1995** [comment]
Ok, I try that. I can`t just restart the server, but tomorrow at 6am (German time) it will be restarting.
Till that I can`t really test it.
I will be reporting tomorrow afternoon/evening.

Greetings
Bloodrayne

**Comment by Bloodrayne1995** [comment]
We are running with 3.6.0 since 6 am and there weren`t any laggs or crashes till now.
I think now it is solved.

Thank you for your support.

Greetings
Bloodrayne

**Comment by SBPrime** [comment]
Thanks for the update. If you a get similar (server lag/crash) problem please reopen this issue.

Regards
SB.
