### ISSUE TITLE
No NBT data when reading TileEntities from async thread.

### ISSUE THREAD

**Issue by Tim269** [SBPrime/AsyncWorldEdit-Premium#178]
Thanks for the fast update to the new WE RC 2! Here is a bug I discovered:

AWE version: 3.6.2
WE version: WorldEdit 7.0.0 Release Candidate 2
Spigot/Paper version: 1.14.2 (git-Paper-525) & 1.13.2 (git-Paper-591)
Java version: Java 8

### Reproduce
1.  Have a chest with content. E.g. books, oak planks
2.  `//copy` it
3. `//paste` it
-> content got wiped.

No console errors appearing. Full log: https://paste.ubuntu.com/p/SYWNM7XjCn/

**Comment by SBPrime** [comment]
For now I can suggest doing /awe toggle off when doing copy. Paste should work without any problems. Please be aware that //copy for a large area might cause tps drop when awe is toggled off.

**Comment by SBPrime** [comment]
Fixed in 3.6.6

**Comment by Momonche** [comment]
@SBPrime I just test it and the issue still here

**Comment by SBPrime** [comment]
Please provide the startup log and the command that you used.

**Comment by Momonche** [comment]
Startup Logs : https://pastebin.com/RSKRUcsV

Place a chest
Put something in
//copy
//paste
Chest is empty

(Same problem with schematic if a chest is replace by a chest)

ASyncWorldEdit 3.6.6
WorldEdit and WorldGuard 7.0.0
Test on 1.13.2 and 1.14.3 servers

**Comment by SBPrime** [comment]
This is not the full server startup log. Also please provide the log (in config set the debug level to debug). I retested this and it still works without any issues.

**Comment by Momonche** [comment]
Logs with debug mode:
https://pastebin.com/e5KmYv8Q

**Comment by Momonche** [comment]
And when I use //copy and //paste
https://pastebin.com/3wcDcn9C

**Comment by SBPrime** [comment]
Again you did not provide the full startup log. I retested this on clean 1.14.3 and paper 1.14.3, no issues. From my point of view it works. The only thing that I can suggest (since you did not provide full server startup log) is to create a clean server with we and awe and test it. You can also do /awe toggle and then test copy.

**Comment by Momonche** [comment]
I create a new server with Paper 1.14.3
With only WorlEdit 7.0.0 and latest ASyncWorldEdit

I have the issue
All logs during the test :
https://pastebin.com/TXRM7sYR

**Comment by SBPrime** [comment]
Send me the link from where you downloaded worldedit.
Did you try my suggestion about clean server?

**Comment by Momonche** [comment]
I try on a clean server, when I use /awe toggle, the bug is already present

And I download World Edit from here:
https://dev.bukkit.org/projects/worldedit/files/2723275

**Comment by SBPrime** [comment]
This means that the NBT fails not because of async. It fails because of your server setup. I would start by creating a WE only server and slowly add new plugins to c when it fails.

**Comment by Momonche** [comment]
I test this on a server with just WE and AWE and I have the bug so

I test without WE and I can't use //copy and //paste
I test without AWE and the bug is here
I test without Paper and there is no Minecraft server
