### ISSUE TITLE
"//replace spawner air" freezes server to crash

### ISSUE THREAD

**Issue by MrSpock78** [SBPrime/AsyncWorldEdit-Premium#181]
AsyncWorldEdit - Premium 3.6.3
WorldEdit 7.0.0 RC3
Paper git-Paper-629 (MC: 1.13.2)

"//replace spawner air" even on small areas (10 10 10) freezes server until crash.
Does not happen with AWE disabled.

https://pastebin.com/6YvNFJsX

**Comment by SBPrime** [comment]
Some other plugin causes AWE class scanner to fail. Please change the debug mode to DEBUG. And then send me the log (~200-300 lines) after trying to perform an operation.

**Comment by MrSpock78** [comment]
https://pastebin.com/KF4UA287

**Comment by SBPrime** [comment]
OK I know whats the problem. You are using the BlockMask and apparently it causes problems. I'll add a fix in the next version.

**Comment by MrSpock78** [comment]
Thank you very much for your help

**Comment by SBPrime** [comment]
Fixed in 3.6.4

**Comment by MrSpock78** [comment]
fixed... thank you so much!
