### ISSUE TITLE
Premium Purchase

### ISSUE THREAD

**Issue by HippyTreats** [SBPrime/AsyncWorldEdit-Premium#182]
Hey there I recently purchased your premium version twice! NNot only that but I am still not able to download the jar file at all. I have both emails from paypal and can either screenshot em or however, ya wanna go about with this issue. Basically just need that 2nd charge reversed and perms to download the jar. thanks ahead of time!

**Comment by SBPrime** [comment]
1. This is not the place for this type of issues you need to use spigot,
2. On github I don't know what username you have on spigot.

**Comment by SBPrime** [comment]
So are you going to contact me os spigot or not?
