### ISSUE TITLE
Add "//count" async support

### ISSUE THREAD

**Issue by MrSpock78** [SBPrime/AsyncWorldEdit-Premium#183]
Using //count on large areas is dropping my tps.
For example using "//count spawner" on a 500x256x500 selection.

Would be nice if it is supported in future versions of AWE.

**Comment by SBPrime** [comment]
When I last checked it was running async. I'll have a look at this.

**Comment by SBPrime** [comment]
Works correctly, if you still have problems please enable debug in awe and send me the count.
