### ISSUE TITLE
//regen not working and causing alot of errors and lag when used

### ISSUE THREAD

**Issue by cheesepufftyler** [SBPrime/AsyncWorldEdit-Premium#184]
worldedit-bukkit-7.0.0-rc-2.jar

AsyncWorldEdit-3.6.5.jar

anytime //regen is used it does this

let me know if its not you, but worldedit. thanks

20.06 20:17:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:304) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
20.06 20:17:39 [Server] INFO at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:499) ~[?:?]
20.06 20:17:39 [Server] INFO at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:69) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
20.06 20:17:39 [Server] INFO at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:105) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
20.06 20:17:39 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
20.06 20:17:39 [Server] INFO at sun.reflect.GeneratedMethodAccessor1656.invoke(Unknown Source) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:460) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:159) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.command.RegionCommandsRegistration._regen(RegionCommandsRegistration.java:560) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.command.RegionCommands.regenerateChunk(RegionCommands.java:365) ~[?:?]
20.06 20:17:39 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:182) ~[worldedit-bukkit-7.0.0-rc-2.jar:?]
20.06 20:17:39 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.regenerateChunk(CraftWorld.java:399) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
20.06 20:17:39 [Server] INFO java.lang.UnsupportedOperationException: Not supported in this Minecraft version! Unless you can fix it, this is not a bug :)
20.06 20:17:39 [Server] Server thread/WARN Chunk generation via Bukkit raised an error

**Comment by SBPrime** [comment]
As you can see in the stack the error is thrown by craftbukkit. This is not something that can be fixed on my end.
