### ISSUE TITLE
Infinity blocks remaining

### ISSUE THREAD

**Issue by FatherWh0** [SBPrime/AsyncWorldEdit-Premium#188]
After upgrading to Worldedit 7.0.1 a problem developed with AWE in which an attempt to paste more than 400 blocks causes a count to begin with no blocks placed. The count goes up to ridiculous numbers: https://prnt.sc/okwnzi
and even larger numbers: https://prnt.sc/okwo2n
eventually reaching infinity blocks remaining: https://prnt.sc/okwotz
Canceling causes an error on the console: https://pastebin.com/SuunNrYN

paper 1.14.4 (also tried with 1.14.3)
AWE 3.6.7
Worldedit 7.0.1 rc1 dist

**Comment by SBPrime** [comment]
I was unable to reproduce the reported problem. Please send me the full server log for startup and when you started the operation.

**Comment by FatherWh0** [comment]
[latest.log](https://github.com/SBPrime/AsyncWorldEdit-Premium/files/3439374/latest.log)

**Comment by SBPrime** [comment]
Ok this is not a bug. And this is not infinite block count ;) Its infinite time to completion. Your server is running low on memory. By default AWE stops all operations if it detects that you have less then 500M of free ram. You can do 2 things:
* increase the amount of ram in your server
* lower the memory usage of your server.

If you don't care you can always disable undo.
