### ISSUE TITLE
Doesn´t work on Paper 1.14.4

### ISSUE THREAD

**Issue by molidev** [SBPrime/AsyncWorldEdit-Premium#192]
I have **paper with 1.14.4** and worldEdit with worldGuard with this version :

https://gyazo.com/4882dc1f5e5cf0de1e5310a802dbad36

and If i try to execute //set this is the error that appear  : 
 https://gyazo.com/5d20b97df2fe3cbf02f59f00142d288a

This is the console log when I tried to execute //set 2

> 18.08 17:58:35 [Server] INFO [AsyncWorldEdit] ***********************************
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] Unable to get the changeset: unsupported version, field changeSetExtent not found.
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] ***********************************
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] *
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * Exception: java.lang.NoSuchFieldException
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * Error message: changeSetExtent
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * Stack: 
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.lang.Class.getDeclaredField(Class.java:2070)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.Reflection.get(Reflection.java:247)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.injectChangeSet(ThreadSafeEditSession.java:331)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.injectExtents(ThreadSafeEditSession.java:296)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.<init>(ThreadSafeEditSession.java:277)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncEditSession.<init>(AsyncEditSession.java:113)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory.getEditSession(AsyncEditSessionFactory.java:133)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:898)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.WrappedLocalSession.createEditSession(WrappedLocalSession.java:151)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.Optional.map(Optional.java:215)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:243)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.Optional.flatMap(Optional.java:241)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
18.08 17:58:35 [Server] INFO [AsyncWorldEdit] * java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)

**Comment by SBPrime** [comment]
You are using an unsupported version of WorldEdit. Please use the release version not dev builds.
