### ISSUE TITLE
//br forest does not create trees

### ISSUE THREAD

**Issue by LauJosefsen** [SBPrime/AsyncWorldEdit-Premium#193]
Hi.

I am running a server with the current setup:
WorldEdit: 7.0.1;61bc012
AsyncWorldEdit 3.6.10
Paper #171

Whenever i use the //br forest command, i cannot get it working with ASWE enabled. It changes some things, like tallgrass, but does not plant the trees.  ""/awe toggle" will make it work.

**Comment by SBPrime** [comment]
Duplicate of: https://github.com/SBPrime/AsyncWorldEdit/issues/213
Unfortunately the fix is not that straight forward.
