### ISSUE TITLE
compass

### ISSUE THREAD

**Issue by budies2001** [SBPrime/AsyncWorldEdit-Premium#196]
Hello. 

I have an issue, when I right or left click on my compass it activates the job queue. It does not do anything that I know of it just shows jobs in queue and keeps spamming it in chat each time I right or left click on the compass.

Thanks.

mikelundberg

**Comment by SBPrime** [comment]
Please include full server startup log and log when you click.

**Comment by SBPrime** [comment]
No followup, closing.
