### ISSUE TITLE
World Edit 7.01 branch does not work in Paper / spigot 1.15 , need a update to 7.1 WE API

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit-Premium#199]
Have tested the World Edit 7.01 branch and it does not work in 1.15 , the blocks get all messed up on any copy / paste action. just to let you know .WE 7.1 support is needed now

**Comment by SBPrime** [comment]
Support for 1.15 will be provided to premium users in couple of days.

**Comment by SBPrime** [comment]
Support added in 3.6.15-BETA-01.

**Comment by Tsoccerguy3** [comment]
Thank you

**Comment by Tsoccerguy3** [comment]
what version build of WE , i got these errors
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * Exception: java.lang.IllegalArgumentException
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.worldedit.command.BaseCommandsVisitor.emitInnerClass(BaseCommandsVisitor.java:200)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.worldedit.command.BaseCommandsVisitor.visitEnd(BaseCommandsVisitor.java:107)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.accept(ClassReader.java:352)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:341)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:305)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.injectClasses(InjectorCore.java:222)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:177)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:239)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:96)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * java.lang.Class.forName(Unknown Source)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
6:29:41 PM [javastacktrace] [INFO] [AsyncWorldEdit] * java.lang.Thread.run(Unknown Source)
