### ISSUE TITLE
AsyncWorldEdit-3.6.15-BETA-01 not working with worldedit-bukkit-7.1.0-beta-1

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit-Premium#200]
AsyncWorldEdit-3.6.15-BETA-01.jar
worldedit-bukkit-7.1.0-beta-1.jar

ASWE does not work with this combination of plugins on Paper 1.15.1 b25

7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * Exception: java.lang.IllegalArgumentException
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.worldedit.command.BaseCommandsVisitor.emitInnerClass(BaseCommandsVisitor.java:200)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.worldedit.command.BaseCommandsVisitor.visitEnd(BaseCommandsVisitor.java:107)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.accept(ClassReader.java:352)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:341)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:305)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.injectClasses(InjectorCore.java:222)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:177)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:239)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:96)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * java.lang.Class.forName(Unknown Source)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
7:00:22 AM [javastacktrace] [INFO] [AsyncWorldEdit] * java.lang.Thread.run(Unknown Source)

**Comment by SBPrime** [comment]
This version requires a specific dev builo of WE (see release notes). Please update AWE.
