### ISSUE TITLE
Convex Selection Type Don't Work

### ISSUE THREAD

**Issue by delbertina** [SBPrime/AsyncWorldEdit-Premium#203]
Using latest AWE and WE on a 1.14.4 PaperSpigot server. 3.6.17 and 7.1.0 beta 1.

Trying to fill in a convex selection type results in 0 blocks every time. No error in the console. Whenever I restart the server w/o AWE convex selections work. The issue also persists with similar selection types like hull etc.  : )

**Comment by SBPrime** [comment]
Fixed in 3.6.19
