### ISSUE TITLE
How to get the Clipboard of an Player?

### ISSUE THREAD

**Issue by FREE2WIN2** [SBPrime/AsyncWorldEdit-Premium#204]
I want to save all schematics in an extra directory for my Schematic-Organizer.
With normal worldedit, my code works, but wih AWE I don't get the player's clipboard.
`WorldEditPlugin worldeditPlugin = (WorldEditPlugin) Bukkit.getServer().getPluginManager().getPlugin("WorldEdit");
		Clipboard clipboard = worldeditPlugin.getSession(p).getClipboard().getClipboard();`

**Comment by SBPrime** [comment]
What exactly do you mean? When do you execute this piece of code?

**Comment by FREE2WIN2** [comment]
This code snippet was correct, I had a mistake in another line:)
