### ISSUE TITLE
AsyncWorldEdit-3.6.17  is broken with the latest World Edit RC1 with 1.15.2 adapters

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit-Premium#206]
Just to let you know the latest ASWE is boken with World Edit RC1 in 1.15.2 . We just disabled ASWE until its got a fix

**Comment by SBPrime** [comment]
Support for WorldEdit RC1 was skipped due to the changes in the newest DEV builds of WorldEdit. New version that supports minecraft 1.15.2 and WorldEdit DEV build 7.1.0-DEV-4825 is released (3.6.18).

Ps. I tested the mentioned RC1 on latest build of spigot and it did not support minecraft 1.15.2.
