### ISSUE TITLE
[3.6.18] Brush Sphere command not placing blocks

### ISSUE THREAD

**Issue by lightlessfilms** [SBPrime/AsyncWorldEdit-Premium#208]
Hi SBPrime,

First of all I would like to thank you for your work that you put into this plugin. It helped my very small server to handle WE much more efficiently without crashes.

I recently updated my server to Papermc version 1.15.2 and plugins as well. After updating the server the brush command: _//brush set sphere 5 minecraft:stone_ doesn't spawn in the blocks. Changing Sphere to Cuboid does spawn in the blocks.

When I remove AsyncWorldEdit plugin, then I can spawn in the sphere without problems.
The console does not put out an error code. 

This is what is shown in chat after executing the command:
**Cuboid:**
https://imgur.com/a/V4IcH9u
**Sphere:**
https://imgur.com/a/EwO56MU

**Pastebin log file:**
https://pastebin.com/Ut5T2utD

**Versions of PaperMC and plugins:**

- PaperMC: git-Paper-96 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- AsyncWorldEdit-3.6.18
- BKCommonLib-1.15.2-v1-SNAPSHOT
- chunkmaster-0.14-beta
- Dynmap-3.0-beta-10-spigot
- EssentialsX-2.17.1.54
- EssentialsXAntiBuild-2.17.1.54
- EssentialsXChat-2.17.1.54
- EssentialsXProtect-2.17.1.54
- EssentialsXSpawn-2.17.1.54
- FastLeafDecay
- LuckPerms-Bukkit-5.0.72
- mcMMO
- Vault
- WorldBorder
- worldedit-bukkit-7.1.0
- WorldEditSUI-1.6.1
- worldguard-bukkit-7.0.2

**Comment by SBPrime** [comment]
The log that you provided is set to private.
I tested the sphere and it works fine.

**Comment by lightlessfilms** [comment]
Problem solved after updating to the newest version 3.6.19.
I am now able to place spheres again.
