### ISSUE TITLE
In need of assistance.

### ISSUE THREAD

**Issue by Castiella** [SBPrime/AsyncWorldEdit-Premium#209]
Really sorry to post here but I can't get Async to work and I'm not sure what i've done wrong.

My server is spamming: https://pastebin.com/EWWdtRfi

I'm using this build of world edit as suggested: https://builds.enginehub.org/job/worldedit/13581

**Comment by lightlessfilms** [comment]
Stop your server. Update to the latest PaperMC version.
Remove the Async and WorldEdit plugin. remove your config files aswel.

Download Async from here:
**Paid** version:
https://www.spigotmc.org/resources/asyncworldedit-premium.9661/
**Free** version:
https://www.spigotmc.org/resources/asyncworldedit.327/

Side note from Spigot page:
Starting from the 1'st of January 2018 the AsyncWorldEdit Premium and the free versions are again one software. All the changes and features added to the premium are now available for everyone.

Download WorldEdit for 1.15.2:
https://dev.bukkit.org/projects/worldedit/files/2869453/download.

Once new jar files are added to your plugin folder, start your server again. It should be fixed.

**Comment by Castiella** [comment]
Hi,

I just did this, and its still spamming.

Heres the latest log and version.

**Log:** https://pastebin.com/v6FFhjMh
**/version :**
 >.... [09:45:29 INFO]: This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [09:45:29 INFO]: Previous version: git-Paper-103 (MC: 1.15.2)
>.... [09:45:29 INFO]: You are running the latest version

**Comment by lightlessfilms** [comment]
Can you post a list of your plugins and the java version.

**Comment by lightlessfilms** [comment]
I see that you use the latest snapshot for worldguard. Can you install version 7.0.2 and try again?
https://dev.bukkit.org/projects/worldguard/files/

also delete your worldguard config folder

**Comment by Castiella** [comment]
Still happening

**Comment by SBPrime** [comment]
@Castiella 
1. You should always use the premium version if you are a premium user.
2. The plugin is not working for you because you have a broken configuration.
```
[09:41:15] [Server thread/INFO]: [AsyncWorldEdit] Error loading config
```

There are 2 options:
either you send the config, or delete it and after restarting modify the clean version.
