### ISSUE TITLE
ASWE is not supporting Worldedit 7.1 command , /tool tree [tree_type]

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit-Premium#210]
when trying to place a tree , it says its done but there is no tree

**Comment by SBPrime** [comment]
This tool is broken try disabling it in the awe config.

**Comment by Tsoccerguy3** [comment]
ok can you state what the old line and the new line is ?

from ?

to?

**Comment by Tsoccerguy3** [comment]
There is a problem with you default config , after removing the # sign at tree and tool AWE will not load .
needed to remove the double brackets to get the plugin to work

from
  disabledOperations: {}
to
  disabledOperations:


  #List of WorldEdit operations that AWE won't run in async mode
  disabledOperations: {}

     - tool
     - tree

**Comment by SBPrime** [comment]
You need to have proper YAML:
```
disabledOptions:
  - treePlanter
```
