### ISSUE TITLE
When I worldedit, sometimes the anvils fall down before the other blocks load...

### ISSUE THREAD

**Issue by craftyfoxe** [SBPrime/AsyncWorldEdit-Premium#211]
When I worldedit, sometimes the anvils fall down before the other blocks load. I have physicsfreez set to true. How can I make it so the anvil float in midair while the worldedit loads?
![2020-03-08_14 33 31](https://user-images.githubusercontent.com/48233056/76168948-52a15380-614a-11ea-917f-d5001c582df1.png)
btw in this picture I had to separately add back in the anvils on the top part where it fell

**Comment by SBPrime** [comment]
It might be related to the change in WE block placing order, unfortunately there is not much you can do (except pre-filling the area).

**Comment by craftyfoxe** [comment]
Hmm even if I move 1 anvil up in the air, it doesn't stay up though

**Comment by SBPrime** [comment]
the anvil won't stay up by itself. For it to stay up you need something like this:

```
UP
^  A
|  #
```

If there is no block under the anvil it won't stay in the air.

**Comment by SBPrime** [comment]
I tried to reproduce this problem and I was unable to do it with normal operations. Although I noticed that when setting an area with sand on speed set to 1bbp the physics freeze is not working as I expected it to do. I will do some more digging in the subject.

**Comment by SBPrime** [comment]
I changed physics freeze in 3.7.
If the problem still occurs in 3.7 please create a new ticket.
