### ISSUE TITLE
Over //paste(ing) Chests = Remove content

### ISSUE THREAD

**Issue by Tim269** [SBPrime/AsyncWorldEdit-Premium#214]
## Info
Server version: git-Paper-162
WorldEdit: WorldEdit 7.1.0;8e55131 (dev bukkit release 26 jan 2020)
AWE: 3.6.20 (26 March 2020, spigotmc premium release)
Java: 1.8.0_242

## Provoke bug
1. Create a new chest
2. Fill it with content like a oak_planks
3. Select it, //copy it
4. Go to another location and //paste
5. Check the chest content -> it worked so far
6. Perform another //paste on the same location
7. Content of the chest cleared

## Additional information
There are no error occurring in the server log. [latest.log](https://github.com/SBPrime/AsyncWorldEdit-Premium/files/4444205/latest.log) It only occurs when AWE is used, not a WE bug.

**Comment by SBPrime** [comment]
Fixed in 3.7
