### ISSUE TITLE
Server crash -> Bukkit errors replacing tile entities by another tile entity or block

### ISSUE THREAD

**Issue by Aurelien30000** [SBPrime/AsyncWorldEdit-Premium#215]
Hey, I would want to report you an issue with the premium version of AWE (I think issue also occurs on free version, I didn't try).

Server version -> git-Paper-164 (MC: 1.15.2)
WorldEdit's version -> 7.1.0;8e55131
AsyncWorldEdit's (premium) version -> 3.6.20

**Simple example to reproduce :**
- Fill an area with jukeboxes. Then remplace them or fill in the same area furnaces or another tile entity / block. The action is well done but this errors appears everytime this type of action is made, for every block modified.

> [19:29:07 ERROR]: Block at 707, 64, 254 is Block{minecraft:furnace} but has net.minecraft.server.v1_15_R1.TileEntityJukeBox@51397c13. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

This error doesn't cause any particular real issue in the game, but with a huge operation (thousands, even millions of blocks), Bukkit and it's fix is "overloaded", and causes a unwanted shutdown of the server :/

Don't hesitate to ask me to provide more details !

Thanks in advance for your help :)

_I'm also sorry if I made some language mistakes..._

**Comment by Aurelien30000** [comment]
Any news please ? :)

**Comment by SBPrime** [comment]
This problem is not related to awe. If you send a log with debug mode enabled I can check.

**Comment by Aurelien30000** [comment]
Indeed, you're rigth, issue also occurs with WorldEdit only, sorry for disturbing :)
