### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred & a depend, softdepend or loadbefore report

### ISSUE THREAD

**Issue by ghost** [SBPrime/AsyncWorldEdit-Premium#216]
Hi

I have the following problem. I have now freshly installed paper, added worldedit and now awe and I get two messages.

Paper: 168
WorldEdit: 7.1.0 (1.13.2 - 1.15.2)
Java: jre11-openjdk-headless [11.0.6.u10-1]

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.primesoft.asyncworldedit.utils.Reflection (file:/home/x/papermc/plugins/AsyncWorldEdit-3.6.20.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
> WARNING: Please consider reporting this to the maintainers of org.primesoft.asyncworldedit.utils.Reflection
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

> [WorldEdit] Loaded class org.primesoft.asyncworldedit.injector.injected.util.eventbus.IDispatchableEventBus from AsyncWorldEdit v3.6.20 which is not a depend, softdepend or loadbefore of this plugin.

Thanks in advance!

**Comment by SBPrime** [comment]
If the plugin works correctly then ignore it. This is because of how AWE uses reflection. Changes are scheduled for some future release.
