### ISSUE TITLE
higher than normal tps loss in ASWE build 20 with W.E. 7.1.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit-Premium#217]
Maybe its time to support the 7.2 branch and all its fixes and optimizations 

here is the timing report of the last Worldedit 7.1.1 build that ASWE build 20 supported
https://timings.aikar.co/?id=4c3f59e3306d4c478de47341185074a5#plugins

**Comment by SBPrime** [comment]
What part of the timings are you referring the dispatcher? 
The 7.2 will be supported when it gets released.
