### ISSUE TITLE
CoreProtect and Blockhub

### ISSUE THREAD

**Issue by TheLethalGoose** [SBPrime/AsyncWorldEdit-Premium#218]
Using the newest version of awe and bh and coreprotect 2.18.2

Sadly co does not recognize any changes i do with awe.

**Comment by SBPrime** [comment]
You need to provide AWE, BH and CP (don't forget to remove db details ;)) config.

**Comment by TheLethalGoose** [comment]
Solved it, like always i did overread a single line. Thanks for your great plugins and the support.
