### ISSUE TITLE
Disallowed Blocks Blacklist doesnt work

### ISSUE THREAD

**Issue by Hyronymos-Old** [SBPrime/AsyncWorldEdit-Premium#220]
The disallowed blocks blacklist doesn't work or maybe I'm a Idiot. I blacklistet minecraft:redstone_wire and people can still use worldedit to place them.

My AsyncWorldEdit config: https://pastebin.com/TLR9wVRY

**Comment by SBPrime** [comment]
Is this in copy/paste or set? I fixed the copy/paste although it works fine for pattern (at least when ppl are using names).

**Comment by Hyronymos-Old** [comment]
It’s only on //set

**Comment by SBPrime** [comment]
Sorry unable to reproduce. I tried it multiple times, multiple approaches. The only thing that I can think of is that you are using a different command set that I'm using.
