### ISSUE TITLE
How to make AWE work with lands?

### ISSUE THREAD

**Issue by cooperisdunn** [SBPrime/AsyncWorldEdit-Premium#221]
I'm getting the error 

"java.lang.ClassCastException: java.land.Integer cannot be cast to com.sk89q.worldedit.math.BlockVector3"

which I think is an issue with the plugin "Lands" by Angeschossen. I've added

me.angeschossen.lands.integration.manager.worldedit.WorldEdit: {}
and
me.angeschossen.lands.c.a.l: {}

to the class scanner black list but unfortunately I still cannot run any worldedit commands (such as //set)

my spigot name is: cooperisdunn
and I'm using AWE premium version: 3.6.20

**Comment by SBPrime** [comment]
You guessed correctly probably you missed something. Support is provided only for premium users. So if you have the premium version send me yous spigot user name. For now I'm closing the issue since its related to server configuration.
