### ISSUE TITLE
error report using //replace 3.7.0

### ISSUE THREAD

**Issue by malaeus** [SBPrime/AsyncWorldEdit-Premium#223]
https://hastebin.com/pocukabaje.apache

this prompted me in game to 'please report this error'

just selecting a 3x3 area to run //replace grass_block and i get this error. 

i run /awe toggle and re-run //replace, no issue.

asyncworldedit-premium 3.7.0
Bukkit-Official(7.1.1-SNAPSHOT+4889-ae1e68e)
Paper version git-Paper-273 (MC: 1.15.2)

**Comment by SBPrime** [comment]
1. what java version
2. send server startup log,
3. enable debug in awe config, do the same operation and send me the log.

**Comment by Tsoccerguy3** [comment]
running ASWE PRE 3.7
             WorldEdit 7.2 Build #5003
              Paper 1.15.2 b 280
No issues

**Comment by SBPrime** [comment]
No followup with log.
