### ISSUE TITLE
Having issues with BPS not rising and also //undo not completely fixing area 

### ISSUE THREAD

**Issue by Bin0ry** [SBPrime/AsyncWorldEdit-Premium#224]
Not sure what's going on but it seems like the version I have is buggy I guess on 1.15.2 paper.....Even doing //replace air just shoots back with an error

**Comment by SBPrime** [comment]
You need to send logs.

**Comment by Tsoccerguy3** [comment]
running ASWE PRE 3.7
             WorldEdit 7.2 Build #5003
              Paper 1.15.2 b 280
No issues

**Comment by Tsoccerguy3** [comment]
Update ASWE 3.7.1 does not work with WE 7.2 branch

**Comment by SBPrime** [comment]
WE 7.2 is not supported in your versions.
Since there is no log, closing the issue.
