### ISSUE TITLE
Error with //fill

### ISSUE THREAD

**Issue by makemp1997** [SBPrime/AsyncWorldEdit-Premium#226]
Hello,

Wel I got a java error, see screenshot 1:
![Screenshot_1](https://user-images.githubusercontent.com/22965328/81732627-07c8f280-9491-11ea-870b-9e865b66cbb4.png)

I also got this error also on a test server with just AsyncWorldEdit, BlocksHub and WorldEdit, but also test it  WorlEdit then works just fine:

Also for you info I have the following data:

- Server version: git-Paper-112 (MC: 1.15.2)
- Plugin Version: 3.7.0
- WE version: 7.1.0
- plugins: Screenshot 2: 
![Screenshot_2](https://user-images.githubusercontent.com/22965328/81733074-b5d49c80-9491-11ea-8e62-9d5431fa0cb9.png)
- Server startup log: https://hastebin.com/holiraduxe.md
- log error: https://hastebin.com/ilekiqetod.bash

**Comment by Tsoccerguy3** [comment]
paper and the WE are older versions try the current builds

**Comment by SBPrime** [comment]
This is the problem with the new edit session injection, I will investigate it ASAP and push a fix.

**Comment by SBPrime** [comment]
Fixed in 3.7.1
