### ISSUE TITLE
Worldedit 7.2 branch was working with ASWE 3.7 , now broken with ASWE 3.7.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit-Premium#227]
Worldedit 7.2 branch was working with ASWE 3.7 , now broken with ASWE 3.7.1
was this accidental or are you working on porting ASWE to the WE 7.2 branch

**Comment by SBPrime** [comment]
Well actually it was the other way around compatibility with 7.2 was an accident :p
If you provide a full server startup log I can make the plugin compatible. Although I do not support dev builds.

**Comment by Tsoccerguy3** [comment]
here is the server log , ASWE and WE 7.2
[latest log.zip](https://github.com/SBPrime/AsyncWorldEdit-Premium/files/4638653/latest.log.zip)

**Comment by Tsoccerguy3** [comment]
I tried ASWE 3.7.2 and its broken with WE 7.2 branch as well

**Comment by Tsoccerguy3** [comment]
Prime could you start supporting the 7.2 branch .I see that 7.2 is now supporting 1.16 server

**Comment by Tsoccerguy3** [comment]
plugin updated to support WE 7.2

closed
