### ISSUE TITLE
AWE breaks a WE method

### ISSUE THREAD

**Issue by Aurelien30000** [SBPrime/AsyncWorldEdit-Premium#229]
Hey,

Using PlotSquared and AWE 3.7.3, the world is unable to load because of this issue caused by AWE (tested without)
https://pastebin.com/vf4fZN0u

Thanks for your help, I hope you'll be able to fix it quickly :)

**Comment by Tsoccerguy3** [comment]
Its a plotsquared issue . open a issue in that git to get it  fixed . It;s plotsquared breaking the WE API

**Comment by Aurelien30000** [comment]
No this isn't related acording to PlotSquared devs, and I agree, issue doesn't occur with default WorldEdit ^^

![image](https://user-images.githubusercontent.com/43724816/86362889-3fc10a80-bc76-11ea-9736-23ddc752f86b.png)

**Comment by Citymonstret** [comment]
> Its a plotsquared issue . open a issue in that git to get it fixed . It;s plotsquared breaking the WE API

It is not. We are using [this](https://github.com/EngineHub/WorldEdit/blob/57d62b0bf516ad8d5f89e34208a114a5b4c76238/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/BlockArrayClipboard.java#L170) method. It's in the WorldEdit API. Whatever AWE is injecting isn't compatible with the WorldEdit API. 


To clarify, we do not support WE 7.2.0 as it has not even been released yet, it's still in beta. We support 7.1.0 as it's the latest WE release. The method handle changed in WE 7.2.0. 

EH made backwards compatible methods that delegate to the new methods, so the signatures **should** still exist.

**Comment by SBPrime** [comment]
This was a problem with the AWE injector improperly handling of 2 methods with similar signature. Fixed in 3.7.4.
