### ISSUE TITLE
Task Shut-down Error

### ISSUE THREAD

**Issue by Bugzillaroid** [SBPrime/AsyncWorldEdit-Premium#234]
From console: 
`ERROR Nag author: 'SBPrime' of 'AsyncWorldEdit' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

Running Paper-1.16.1/83

**Comment by SBPrime** [comment]
Duplicate.
