### ISSUE TITLE
position 1

### ISSUE THREAD

**Issue by paradisegamer1** [SBPrime/AsyncWorldEdit-Premium#235]
everytime i use the axe to set on position 1, it set to the right coordinates, but less then a second later it ALWAYS goes back to coordinates x=-1 y=-1 z=-1 and i dont know why? i reinstalled forge and worldedit but it still doesnt work

![image](https://user-images.githubusercontent.com/68754866/88429454-bbdae800-ce07-11ea-8195-f579751a05df.png)

**Comment by SBPrime** [comment]
Forge was supported a long time ago when cauldron was a thing. Im surpriesed that you made it working with Forge on 1.14. To be able to help you you need to give me detailed information how did you set everything up.

**Comment by SBPrime** [comment]
Please an answer.

**Comment by paradisegamer1** [comment]
Thanks! also just so you know it was only broken for 1.14.4. i found that out! so now im using 1.15.2, but thanks for help and whats cauldron? or is it the minecraft cauldron? ehh whatever.

**Comment by SBPrime** [comment]
Still could you send info about your setup, adding officail support for modded servers would be a good thing.

**Comment by SBPrime** [comment]
No response.
