### ISSUE TITLE
Blocks with physics do not show or place consistently

### ISSUE THREAD

**Issue by Venlious** [SBPrime/AsyncWorldEdit-Premium#238]
When you paste blocks with physics, specifically sand, gravel, concrete powder etc. they do not always paste correctly. Sometimes it works flawlessly, other times some blocks will appear missing to the client (relogging or switching worlds fixes those).

Other times the blocks are actually missing. I suspect this only happens whenever there are many jobs going on at once (not in the same region, but on the server).

Demonstration:
https://voidvortex.com/share/f/2020-07-29_10-45-24.mp4

**Comment by Venlious** [comment]
This issue may have to do with running an outdated version of WorldGuard. I updated to https://dev.bukkit.org/projects/worldguard/files/2989116 and was unable to repeat using the same set-up.

Specifically this log stands out:
> * Workaround for a CraftBukkit change that made no-physics-sand/gravel non-functional.

**Comment by SBPrime** [comment]
I know of this issue, unfortunately I can't do anything regarding the client side. It is related to the fact how spigot handles physics events.
