### ISSUE TITLE
* CLASS INJECTION FAILED!! *

### ISSUE THREAD

**Issue by Hentelten** [SBPrime/AsyncWorldEdit-Premium#248]
Hello.

I get this error on startup:
https://pastebin.com/uB2pztD2

Server version:
git-Purpur-1117 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

AsyncWorldEdit version:
AsyncWorldEdit-3.8.3.jar

WorldEdit version:
worldedit-bukkit-7.2.5-dist.jar

**Comment by SBPrime** [comment]
Problem was related to changes in spigot implementation.

Fix is in the testing.

Detailed information:
https://github.com/SBPrime/AsyncWorldEdit/issues/376
