### ISSUE TITLE
Version 1.18

### ISSUE THREAD

**Issue by ErythroCraft** [SBPrime/AsyncWorldEdit-Premium#253]
Hi

The first version of world edit dev build is out.

I am using build 19061 to test updates do the first parts of updating my server.
https://builds.enginehub.org/job/worldedit/19061

Can you create a dev build of AsyncWorldEdit to test what's happen?

**Comment by SBPrime** [comment]
Hey, thanks for the heads-up.
Unfortunately the build that you mentioned is not on master.

As a rule I support released versions of WorldEdit. Occasionally, after version change I support dev builds, but only if those builds are on master.

I'll update the plugin to the latest version as soon as dev build (or release) is available on master branch of WorldEdit.

If I miss it and you will see it before me please send me a message.

**Comment by alekso56** [comment]
The master branch has this dev build in since 2 days ago,  here is the build from 2h ago with a small fix attached. https://builds.enginehub.org/job/worldedit/19098

**Comment by SBPrime** [comment]
They must have changed there approach. For me its strange and not logical that you have master at version 7.3 for experiments and other branch "as master" (?) at version 7.2.x and the 7.2 has newer functionality...

I'll check that and see what can be done.

**Comment by SBPrime** [comment]
1.18 support added in (experimental) 3.9.3
