### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by DeKleineKobini** [SBPrime/AsyncWorldEdit-Premium#36]
How can I check if ID of task is same as the paste action I did wityh my plugin?

And how can I actually paste something? I only know how to do it with 2.x

**Comment by SBPrime** [comment]
Check this: https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/9

**Comment by DeKleineKobini** [comment]
Thanks

**Comment by DeKleineKobini** [comment]
I found one thing I don't know to do:
execute something when the pasting is done

**Comment by DeKleineKobini** [comment]
Got it working with

``` java
bp.addListener(new IBlockPlacerListener(){

            @Override
            public void jobRemoved(IJobEntry job) {
                if(!job.getName().equalsIgnoreCase("ETH paste map")) return;
                if(gameHandler.getState() != GameState.MAP_RESETTING) return;

                gameHandler.setState(GameHandler.GameState.MAP_INLOBBY);
            }

            @Override
            public void jobAdded(IJobEntry job) {
                if(!job.getName().equalsIgnoreCase("ETH paste map")) return;

                gameHandler.setState(GameState.MAP_RESETTING);
            }
        });
```

**Comment by SBPrime** [comment]
You also need to add a job state change listener (from IJobEntry) and listen for job state done. The job is removed when all blocks are queued (stage 1 is done). All blocks are placed after the job is in state DONE.

**Comment by DeKleineKobini** [comment]
When do I need to add the job state change listener? on jobRemoved?

**Comment by SBPrime** [comment]
Add listener on jobAdded and remove on job removed.

**Comment by DeKleineKobini** [comment]
So tomething like this:
onjobadd: add state change listener
Onjobremove: remove state change listener

**Comment by SBPrime** [comment]
Yes exactly

**Comment by DeKleineKobini** [comment]
Thank you for the help.
