### ISSUE TITLE
After installing AWE, WorldEdit won't load

### ISSUE THREAD

**Issue by Xephi** [SBPrime/AsyncWorldEdit-Premium#45]
I've just installed AWE and it looks like WE won't load anymore : 

> [21:59:53] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.1-SNAPSHOT;3459-94ae1be
> [21:59:53] [Server thread/ERROR]: Error occurred while enabling WorldEdit v6.1.1-SNAPSHOT;3459-94ae1be (Is it up to date?)
> java.lang.ExceptionInInitializerError
>     at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:98) ~[?:?]
>     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
> Caused by: java.lang.IllegalArgumentException: Replacing commands is currently undefined behavior
>     at com.sk89q.worldedit.util.command.SimpleDispatcher.registerCommand(SimpleDispatcher.java:64) ~[?:?]
>     at com.sk89q.worldedit.util.command.fluent.DispatcherNode.register(DispatcherNode.java:71) ~[?:?]
>     at com.sk89q.worldedit.extension.platform.CommandManager.<init>(CommandManager.java:153) ~[?:?]
>     at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:86) ~[?:?]
>     at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:95) ~[?:?]
>     at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:91) ~[?:?]
>     ... 12 more
> [21:59:53] [Server thread/INFO]: [AsyncWorldEdit] Initializing WorldEdit.
> [21:59:53] [Server thread/ERROR]: Could not pass event PluginEnableEvent to AsyncWorldEdit v3.3.2
> org.bukkit.event.EventException
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-23e921f-8b69bdd]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
>     at com.sk89q.worldedit.bukkit.WorldEditPlugin.getWorldEdit(WorldEditPlugin.java:391) ~[?:?]
>     at org.primesoft.asyncworldedit.worldedit.WorldeditIntegrator.<init>(WorldeditIntegrator.java:115) ~[?:?]
>     at org.primesoft.asyncworldedit.core.AsyncWorldEditCore.initializeWorldEdit(AsyncWorldEditCore.java:311) ~[?:?]
>     at org.primesoft.asyncworldedit.AsyncWorldEditMain.onPluginEnabled(AsyncWorldEditMain.java:323) ~[?:?]
>     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
>     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
>     ... 13 more

Tested with AWE and AWE-dev latest version

**Comment by SBPrime** [comment]
You are probably using the wrong version of AWE. Since you are using DEV builds of WE you need to install the AsyncWorldEdit-dev.jar not the AsyncWorldEdit.jar. You can find the proper download on the "version history".
1. Remove AsyncWorldEdit.jar and AsyncWorldEditInjector.jar
2. Install AsyncWorldEdit-dev.jar
3. Restart the server (/reload wont work)
