### ISSUE TITLE
No Functioning WorldEdit

### ISSUE THREAD

**Issue by FlippantCactus** [SBPrime/AsyncWorldEdit-Premium#47]
Using (Attempting to) WorldEdit 3463 and latest AWE, getting http://hastebin.com/qixokovaje.avrasm upon startup, WorldEdit doesn't enable. 
WorldEdit 3463 works on it's own.

**Comment by SBPrime** [comment]
You are using a mismatched version of WE and AWE. Please remove AsyncWorldEdit.jar and AsyncWorldEditInjector.jar go to Version History download the dev version, "AsyncWorldEdit-dev.jar", install the plugin and do a server restart (not reload!).

**Comment by caxerx** [comment]
http://pastebin.com/i5Cpv3U7
I am using the dev version but I had the same error.

**Comment by SBPrime** [comment]
Please follow the instruction that I provided and all will work.
