### ISSUE TITLE
Add disallowed-block to permission groups

### ISSUE THREAD

**Issue by jaboy** [SBPrime/AsyncWorldEdit-Premium#54]
Hello

In the main worldedit configuration, there is a function called "disallowed blocks" that controls what blocks to not allow using with WE, it would be nice if this would be added to awe permissions group, so you can control what groups can use what blocks.

**Comment by SBPrime** [comment]
Thanks for the suggestion. I'll add this.

**Comment by SBPrime** [comment]
Done. Will be available in the next version (3.3.7)
