### ISSUE TITLE
Exceptions on startup

### ISSUE THREAD

**Issue by Favorlock** [SBPrime/AsyncWorldEdit-Premium#57]
The latest version of this plugin doesn't appear to be working with the latest version of worldedit found on their CI. Can you please add support for the latest versions?

Here are the stacks that show up with the latest CI build: http://pastebin.com/4WnyPhU4

This happens with the latest build of spigot, worldedit, and asyncworldedit.

**Comment by Favorlock** [comment]
This appears to be the same issue as in #47 but I double checked to make sure I downloaded the dev build and I downloaded from the correct upload. Either you uploaded the wrong version for the dev build or you broke support with the last build.

**Comment by Favorlock** [comment]
Here is another thing I want to note, it doesn't look like any of the old update downloads work from spigot. Every update downloads 3.3.4 for Dev Bukkit.

This is the version I'm trying to download from spigot https://www.spigotmc.org/resources/asyncworldedit-premium.9661/update?update=81892 but it appears to be downloading this build: https://www.spigotmc.org/resources/asyncworldedit-premium.9661/update?update=81893

**Comment by SBPrime** [comment]
I tested this using the latest dev build of WE (3482) and everything works correctly. You must have installed the wrong version of AWE. You need to download AsyncWorldEdit-dev.jar not AsyncWorldEdit.jar. The download from update page will always download the last uploaded file. You need to download from the version history. Please remember to remove the injector and do a full restart.
