### ISSUE TITLE
//undo no longer works when placing trees

### ISSUE THREAD

**Issue by alchemistmatt** [SBPrime/AsyncWorldEdit-Premium#59]
I can use `//tree` or `/tool tree birch` to create a tool for placing trees.  Prior to version 3.3.6-dev after placing a tree I could use `//undo` to remove that tree.  Now `//undo` is only tracking operations performed with `//set` or `//regen`

**Comment by SBPrime** [comment]
I checked on a server WITHOUT AsyncWorldEdit and the latest WorldEdit (build 3487) and it looks like the trees don't get removed when you do undo.

I also looked at the WorldEdit code and apparently the changed blocks ARE tracked. After that I did a second test using the same version of WorldEdit but I reverted to Spigot-1.8 and in that version it worked great, the undo data for the tree was stored. 

Actually there are 2 problems here:
1. WorldEdit not storing undo data for tree
2. AsyncWorldEdit not storing the tree undo in the history

For 1, you need to nag the WE guys, 2 ill fix.

**Comment by SBPrime** [comment]
Added support for tools.
