### ISSUE TITLE
Error when loading schematic

### ISSUE THREAD

**Issue by PhanaticD** [SBPrime/AsyncWorldEdit-Premium#60]
I got this error when pasting in a schematic: https://gyazo.com/f879ed0c660b2bc103df77b049f24180

**Comment by PhanaticD** [comment]
after relogging a few times (getting that same error) it eventually worked and I was able to log in successfully

**Comment by SBPrime** [comment]
1. Please send the server log
2. Please send a link to the schematic.

**Comment by SBPrime** [comment]
Any update?

**Comment by PhanaticD** [comment]
I forget what schematic this was sorry

**Comment by SBPrime** [comment]
Then I'm going to close the issue for now.
