### ISSUE TITLE
AWE purge seems to break undo

### ISSUE THREAD

**Issue by PhanaticD** [SBPrime/AsyncWorldEdit-Premium#61]
I was pasting in a schematic, when I noticed it was in the wrong spot.

I typed /awe purge to cancel the progress, then when I typed //undo, it said 0 blocks processed and the blocks were still there

**Comment by SBPrime** [comment]
Tested using the latest version. What was tested: purge, purge all and cancel. After the job got canceled I did undo then redo and all worked fine.

One thing that might happen is that the undo was not yet loaded from disk and you did not notice that. When you do any WE operation while AWE is installed you always get 0 blocks processed. After that AWE starts processing blocks (when you do undo it loads the undo data from disk), stage 1. When all blocks are processed it starts placing them on the world.

**Comment by SBPrime** [comment]
Any update?

**Comment by SBPrime** [comment]
Tested on the latest, unable to reproduce.
