### ISSUE TITLE
Add support for //restore

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit-Premium#62]
Async stage 1 of the "//restore" command.

**Comment by FatherWh0** [comment]
I would like to second this request. I will eventually need to restore some very large regions.

**Comment by FatherWh0** [comment]
Has there been any further thought on this? I need to reset my nether and //restore all the regions but without A.W.E. it's proving impossible.

**Comment by SBPrime** [comment]
No one was complaining therefore it was not done. I'll try to push it to the next release.

**Comment by SBPrime** [comment]
Added in 3.5.2
