### ISSUE TITLE
This plugin breaks when used in conjunction with PlotSquared

### ISSUE THREAD

**Issue by zombachu** [SBPrime/AsyncWorldEdit-Premium#63]
(This happened when using version 3.3.7-dev of this plugin)

If I have both AsyncWorldEdit Premium+WorldEdit and PlotSquared version 3.3.3 installed at the same time, PlotSquared causes [this error](http://hastebin.com/ulitatipok) on startup. This does not happen if I only have WorldEdit and PlotSquared, or just PlotSquared. Also, this issue didn't happen while I used the non-premium version of AsyncWorldEdit.

All three plugins (PlotSquared, WorldEdit, and AsyncWorldEdit Premium) fail to start in the cases I mentioned above.

**Comment by zombachu** [comment]
Actually, just WorldEdit and PlotSquared fails, but since AsyncWorldEdit is useless without WorldEdit working properly then there's not much of a distinction from what I said earlier.

I love your plugins btw, I'm just sad I can't use this one :/

**Comment by SBPrime** [comment]
Its not a bug in AWE, WE or PlotMeSquered. You mismatched the AWE and WE versions. Apparently you are using the dev version of WE you need to install AWE dev (go to version history and click download on the latest dev version).

**Comment by zombachu** [comment]
Ah, my bad. I had both versions downloaded and I guess I just uploaded the wrong version to the server. Sorry!
