### ISSUE TITLE
MaxChangedBlocksException when using the API to paste a schematic

### ISSUE THREAD

**Issue by GyllieGyllie** [SBPrime/AsyncWorldEdit-Premium#64]
Hey,

I'm using the AWE API to regenerate my arena's for my minigames. Now everything was working fine till I changed this line:

`final Operation operation = holder.createPaste(editSession, worldData).to(to).ignoreAirBlocks(true).build();`

to

`final Operation operation = holder.createPaste(editSession, worldData).to(to).ignoreAirBlocks(false).build();`

Now it keeps throwing a MaxChangedBlocksException while I'm sure in WorldEdit settings it's set to -1. Both the worldedit settings and AWE settings are default.

**Comment by SBPrime** [comment]
Hi sorry for not answering sooner, but I missed your comment. Please check if you did not enable block limit in AWE.

**Comment by GyllieGyllie** [comment]
Hey,

thanks for the reply, in the meantime found the problem, had to get the max blocks higher when creating the IThreadSafeEditSession.

**Comment by SBPrime** [comment]
So you did not initialize the session using -1?

**Comment by GyllieGyllie** [comment]
Actually haven't tried that yet. Let me give it a shot. I'll keep you updated

**Comment by GyllieGyllie** [comment]
Changing it to -1 does work indeed! Thanks for the help and great plugin!

**Comment by SBPrime** [comment]
No problem.
