### ISSUE TITLE
Broken chunk data reading for 1.9r1 and 1.9r2

### ISSUE THREAD

**Issue by Postremus** [SBPrime/AsyncWorldEdit-Premium#71]
Hello,

When doing "/chunk paste", some of the surrounding blocks in the affected chunks get removed.
To reproduce:
1) load a schematic, doesn't seem to matter which
2) /chunk paste
3) look at the ground

This happens on our test case, the ground was made out of Quartz, Chiseled Quartz, and Black wool. Only the Black wool remained:

![2016-05-27_18 39 01](https://cloud.githubusercontent.com/assets/1223135/15614744/b5dce3de-243a-11e6-9317-69a04f164402.png)

Tested on "CraftBukkit version git-Spigot-8a048fe-106ced0 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)" and also on "Paper version git-Paper-"1349245" (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)".
Awe version:

```
[18:35:30:201940 INFO]: AsyncWorldEditInjector version 3.3.5
[18:35:30:201941 INFO]: This plugin attaches into WorldEdit and makes it asynchronous.
[18:35:30:201941 INFO]: Website: https://github.com/SBPrime/AsyncWorldEdit-Premium/wiki
[18:35:30:201941 INFO]: Author: SBPrime
[18:35:30:201942 INFO]: AsyncWorldEdit version 3.3.9
[18:35:30:201942 INFO]: This plugin attaches into WorldEdit and makes it asynchronous.
[18:35:30:201943 INFO]: Website: https://github.com/SBPrime/AsyncWorldEdit-Premium/wiki
[18:35:30:201943 INFO]: Author: SBPrime
```

Worledit version:

```
WorldEdit version 6.1.2;b3fbe8b
```

Java:

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

If you need any more Information, please let me know.

Greetings
Postremus

Edit: seems to affect the whole chunk, some other quartz block in that chunk are missing as well.

**Comment by Postremus** [comment]
There were no entries in the log about this.

**Comment by Postremus** [comment]
Another test case, a 16x16x16 block made completly out of quartz:
![2016-05-27_19 02 01](https://cloud.githubusercontent.com/assets/1223135/15615275/9749185e-243d-11e6-87d5-3143f9dae5d5.png)
As you can see, the block itself got pasted correctly. But again, the quartz from the ground got removed.

**Comment by SBPrime** [comment]
Broken blocks ID's > 127 interpretation

**Comment by SBPrime** [comment]
Fixed.

**Comment by Postremus** [comment]
tested 3.3.10, works now. thank you. :)
