### ISSUE TITLE
Direct chunk api - examples

### ISSUE THREAD

**Issue by Postremus** [SBPrime/AsyncWorldEdit-Premium#72]
Hello,

Would anybody please be kind enough to provide me with examples of how to use the direct chunk api? I just can't get my head around it.
For example, i want to paste a schematic. Do i need to get myself all the affected chunks, then get them through the IWorld.getChunkAt() interface, put them into the directchunkapi, and then do more stuff?

Any help is appreciated.

Greetings
Postremus

**Comment by SBPrime** [comment]
DC API does not provide a set of ready to use commands to. It provides low level API to access chunk data directly.

The scenario for DC API is something like this:

1 Get IDirectChunkAPI
2 perform as async job
3 wrap the chunk that you want to modify
4 acquire the lazy chunk data
5 modify the chunk data
6 flush the chunk data to the map (using doCustomAction)
