### ISSUE TITLE
Issues with actionbar on 3.3.10 (exception) - minor

### ISSUE THREAD

**Issue by frizzbee30** [SBPrime/AsyncWorldEdit-Premium#73]
Hi, since updating to 3.3.10 we seen to have lost the actionbar function on pasting etc. managed to catch the error below when another player was replacing.

A very minor issue, but if you have a fix that would be great

Running latest commit of worldedit and latest commit of spigot 1.9.4

Thanks :)

03.06 07:56:39 [Server] INFO [AsyncWorldEdit] ***********************************
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* java.lang.Thread.run(Thread.java:745)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:79)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:259)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:80)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:369)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:436)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.fetchEntry(BlockPlacer.java:538)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.hideProgressBar(BlockPlacer.java:1074)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.progressDisplay.ProgressDisplayManager.disableMessage(ProgressDisplayManager.java:81)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* org.primesoft.asyncworldedit.progressDisplay.ActionBarAPIIntegrator.disableMessage(ActionBarAPIIntegrator.java:125)
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* Stack: 
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* Error message: org.primesoft.asyncworldedit.api.playerManager.IPlayerEntry.getPlayer()Lorg/bukkit/entity/Player;
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] \* Exception: java.lang.NoSuchMethodError
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] ***********************************
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] Progress display Action BAR thrown an error: 
03.06 07:56:39 [Server] INFO [AsyncWorldEdit] ***********************************

**Comment by SBPrime** [comment]
Try:
1. removing the /plugins/AsyncWorldEdit/plugins folder
2. restart server 
3. enable action bar bridge in AWE plugins
4. restart server

Please make sure that you don't have the old bridge plugin in bukkit plugins

**Comment by frizzbee30** [comment]
Hi, the plugins folder isn't regenerating after the removal/restart (multiple restarts). Not a major issue as I can add the plugin in, but obviously I'm aware it should.

Thanks :)

**Comment by frizzbee30** [comment]
sorry, facepalm! just spotted the old one which I thought was removed, I'm guessing thats blocking the folder generation

**Comment by frizzbee30** [comment]
Hi removed and restarted, but still not generating the plugins folder within the AWE folder?  Thanks

**Comment by SBPrime** [comment]
did you also remove the "installed" file in AsyncWorldEdit?

**Comment by frizzbee30** [comment]
Hi, yea I completely deleted the plugins folder (in AWE), should I have left that in and just deleted the api file?

**Comment by frizzbee30** [comment]
I can actually pull the api /folder from our test server, so it's not a big problem. I'm certain the dual api .jar's were the issue (dumb of me not to spot, odd it behaved before lol)

**Comment by SBPrime** [comment]
If you remove the AsyncWorldEdit folder from  plugins it should regen.

**Comment by frizzbee30** [comment]
Thanks, I figured it would, will do.
