### ISSUE TITLE
Async operations hang when performing over large area.

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit-Premium#74]
Area size over: 160x300
Operations tested: set, copy

**Comment by Postremus** [comment]
same problem here.
workaround: try to get close to the affected chunks of the operation
test with awe 3.3.10, we 6.1.2, on paper

2016-06-07 10:49 GMT+02:00 SBPrime notifications@github.com:

**Comment by frizzbee30** [comment]
I'm getting the same issue with the latest version, have had to resort to chunk copy (which is rather brilliant!)

**Comment by TNTUP** [comment]
Same here^^ I've downgraded it for the time being while you're on vacation^^

**Comment by Postremus** [comment]
@TNTUP to which version did you downgrade?

2016-06-11 11:15 GMT+02:00 TNTUP notifications@github.com:

**Comment by TNTUP** [comment]
@Postremus To 3.3.9 seems fine, I'll report again if I encounter the same issue.

**Comment by SBPrime** [comment]
Looks like the operations ARE executed but extremely slow. 

Cause: AWE detected all chunks as unloaded, that forced the fast actions to fall back to dispatcher - much slower.

Problem solved (will be available in next release after 3.3.10).
