### ISSUE TITLE
world edit #3563 ( and possibly earlier)Undo action fails silently with 3.3.11

### ISSUE THREAD

**Issue by frizzbee30** [SBPrime/AsyncWorldEdit-Premium#77]
Hi ,firstly thanks for the great update! As part of testing with the later versions of WE I've noticed that certainly with build 3563, if an undo action is selected, the job completes without any blocks being changed? The in game message shows as job complete. I'm sorry but I haven't tested with earlier versions, apart from our current 3558 build.

Thanks

[Normal //set operations completely without issues]

**Comment by SBPrime** [comment]
To clarify: you allow a regular operation to compleat and when you do undo no blocks get changed?

**Comment by frizzbee30** [comment]
yea, but the in game message says undo completed successfully.  Thanks

**Comment by SBPrime** [comment]
Tested using the latest WE (#3572) and everything worked correctly.

**Comment by frizzbee30** [comment]
Thanks, that's great. Not had a chance to test with that version yet.  :)

**Comment by SBPrime** [comment]
Any update?

**Comment by frizzbee30** [comment]
Hi, all looks great :D  thanks
