### ISSUE TITLE
Typo in AWE-API 2.0.3 mvn-artifact pom file

### ISSUE THREAD

**Issue by kpalang** [SBPrime/AsyncWorldEdit-Premium#86]
I'd like to point out a typo in (https://github.com/SBPrime/AsyncWorldEdit-API/blob/maven-artifact/org/primesoft/asyncworldedit/AsyncWorldEdit-API/2.0.3/AsyncWorldEdit-API-2.0.3.pom) where `<version>` states 2.0.2, while folder indicates to 2.0.3 build.

TCS

**Comment by SBPrime** [comment]
First thing first: wrong project :P
Second thing: fixed.
