### ISSUE TITLE
//regen doesn't restore blocks outside the selection

### ISSUE THREAD

**Issue by stevmei** [SBPrime/AsyncWorldEdit-Premium#87]
First of all some facts:

WE version: WorldEdit version 6.1.4-SNAPSHOT;3596-b9801eb
AWE version: AsyncWorldEdit version 3.4.0

When regenerating some blocks, the whole chunk is regenerated (as usual) but all blocks **outside** the selection to regenerate are not changed back to their old values.

Tested without AWE enabled: WE works fine, just the selected blocks are regenerated.
Tested with AWE enabled: Whole chunk is regenerated, blocks outside the selection are not restored.

**Comment by sigmaroot** [comment]
Hello? Is somebody here? ...

**Comment by SBPrime** [comment]
Fixed in 3.4.1
