### ISSUE TITLE
//regen randomly skipping some of the chunks in the selection

### ISSUE THREAD

**Issue by alchemistmatt** [SBPrime/AsyncWorldEdit-Premium#89]
We have been using AsyncWorldEdit premium for 5 months now and have consistently moved to the latest version each time.  With AsyncWorldEdit premium v3.4.0, coupled with its corresponding AsyncWorldEditInjector.jar (size 74927 bytes, MD5 ecc5fc6a47c47a0363105a02524c9ce2), use of `//regen` is leaving non-regenerated (untouched) sections.  My experience with `//regen` is that it often leaves half-regenerated trees and villages, but the landscape is always correct, and it always removes player builds.  Now the `//regen` is skipping parts of its selection and not removing player builds (portions of a house, torches on the ground, a crafting table, etc.).  Worse, it's not consistent, I can do `//regen` and it misses some parts, then I do `//outset 5` or `//shift 5` then `//regen` again, and now I might have a chance of successfully regenerating the parts that were missed the first time.

In contrast, with AsyncWorldEdit premium v3.3.11, coupled with its corresponding AsyncWorldEditInjector.jar (size 74508 bytes, MD5 c88cbc6513f816901dcf8767451e7395), my land `//regens` consistently work properly.

We are running Spigot version 1.10.2 on Linux.  I have tested v3.4.0 with a minimal set of plugins, and I still see the incorrect behavior.  No messages appear in the logs, so I am at a loss as to the cause.  

The following screenshots show a portion of land where I first used `//set 0` on the selection, then used `//regen`:
![regen1_before](https://cloud.githubusercontent.com/assets/6363449/17164347/2dc22efc-537c-11e6-8a22-1b157d51a430.png)
![regen2_selectedregion](https://cloud.githubusercontent.com/assets/6363449/17164348/2dc92748-537c-11e6-92c7-33b402b2a5b2.png)
![regen3_after](https://cloud.githubusercontent.com/assets/6363449/17164349/2dc94c00-537c-11e6-802b-05a1c88b5687.png)

**Comment by stevmei** [comment]
Similar to #87, but on the other side :smile:

**Comment by SBPrime** [comment]
Fixed in 3.4.1
