### ISSUE TITLE
Problems with //move

### ISSUE THREAD

**Issue by jaboy** [SBPrime/AsyncWorldEdit-Premium#92]
version: 3.4.0

I found a problem with the //move
If you //move a build so the destination is within the source blocks, funny things start happening.
Example, if you make a 10x10x10 cube of stone, and //move 5, it will remove the blocks that are still within the source blocks. 

undoing the affected block works fine, and using /awe toggle removes the problem

(look at the attached pictures)
(first picture, is a cube of //set 159:7,159:12, and a solid block of stone)
(2'ed picture is after a //move 5)
![before](https://cloud.githubusercontent.com/assets/916338/17278243/c2ff6c70-5758-11e6-9acd-c8a24af47e5d.png)
![after](https://cloud.githubusercontent.com/assets/916338/17278244/c303ab00-5758-11e6-978a-8b47d855582a.png)

**Comment by SBPrime** [comment]
Duplicate #88
