### ISSUE TITLE
Wrong config generation for BossShopPro

### ISSUE THREAD

**Issue by enarkay** [SBPrime/AsyncWorldEdit-Premium#96]
Before I start, I would greatly appreciate an instruction for the correct/accurate way to install and use AsyncWorldEdit for Cauldron. So far I've been following the instructions given in your spigot page, and have the following setup:

**Server**: cauldron-1.7.10-2.1403.1.54
**AsyncWorldEdit**: lastest version (v3.4.1), located in plugins folder
**AsyncWorldEditInjector**: lastest version (v3.4.1), located in mods folder
**WorldEdit**: version (worldedit-bukkit-6.0), located in plugins folder
**WorldEdit forge**: version (worldedit-forge-mc1.7.10-6.0-beta-01), located in mods folder

If I'm doing something wrong above, please correct me.

Now about the problem: I've just experienced a crazy incident today, where AsyncWorldEdit config was being generated inside the BossShopPro plugin folder. Therefore, the config for BossShopPro is not generated and could not be run, although the right config for it generated and the plugin seemed to run fine without AsyncWorldEdit. To be precise, the problem isn't with AsyncWorldEdit but AsyncWorldEditInjector: if I remove AsyncWorldEditInjector from the mods folder (either completely or relocating it into the plugins folder), then BossShopPro has no problem generating its own config file or running on the server.

Thank you for your hard work and time:)

**Comment by SBPrime** [comment]
1. Does BossShopPro use WorldEdit?
2. Does AWE config generate correctly when you BossShopPro i snot installed?
   3, What your plugins folder (is it changed to something other then Plugins?)
3. Are you able to provide the startup log?

**Comment by enarkay** [comment]
1. I've asked the BossShopPro author whether the plugin uses WorldEdit, so I'll let you know as soon as I find out.
2. Yes, I believe so. To be precise, When using the two plugins together, the config for BossShopPro doesn't generate and is overwritten by one for AWE. When using just any one of the two plugins without the other, both generate their correct config in the correct folder.
3. I'm not sure what you mean. If you're asking for the name of the plugins folder, I did not make any changes to the folder name so it's the default generated name which is "plugins"
4. Server log:   http://pastebin.com/yxuP91zD

Also, could you confirm whether I've installed AWE correctly for the cauldron server and correct me if I'm wrong?

**Comment by enarkay** [comment]
I've just heard back from the BossShopPro author and he says the plugin itself does not use WorldEdit, although it's possible to setup a shop item that could possibly run commands from other plugins including WorldEdit. If it's worth mentioning, the above error log is produced from a clean initial run of both plugins, without any setups or changes to the configs.

**Comment by SBPrime** [comment]
> [20:56:20] [Server thread/INFO]: FML has found a non-mod file AsyncWorldEdit.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

This might be one problem. Apparently you have the plugin in the MODS directory.

> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v3.3.5
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] ****************************
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* CLASS INJECTION FAILED!! *
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] ****************************
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* AsyncWorldEdit won't work properly.
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* Exception: java.lang.NoSuchMethodError
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* Error message: com.sk89q.worldedit.EditSession.ForceClassLoad()Ljava/lang/Class;
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* Stack:
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:133)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:88)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.world.World.<init>(World.java:349)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] \* java.lang.Thread.run(Unknown Source)
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] ****************************
> [20:56:25] [Server thread/INFO]: [AsyncWorldEditInjector] Enabled

This is a second problem. Looks like the injector is located in PLUGINS folder ("Injector platform set to: InjectorBukkit").

Please verify that your setup is like you described because the log suggests something else.

Finally: What version of WE are you using? Is it 6.0? Or at least 6.1.2?

**Comment by enarkay** [comment]
1. I was pretty sure I located AWE and AWE_Injector into their right folders, but after you mentioned the possibility of mislocation, I reprepared a clean new server, checked multiple times that I put each into their right folders, and now the config overwriting problem seems to be gone! Maybe I misplaced them like you said, I am terribly sorry for this mistake and unnecessary inconvenience:)
2. But now I face a bigger problem, where WE does not work at all. The version of WE and WE_forge I use is 6.0 for both, as I've written in my first comment. Correct me if I'm wrong but I should use the same version for WE and WE_forge in a cauldron server, no? The latest version that I found to exist for both was 6.0, hence I used it. Here's the link I used for comparing the versions, as well as the downloads.

**WE:** https://dev.bukkit.org/bukkit-plugins/worldedit/files/
**WE_forge:** https://mods.curse.com/mc-mods/minecraft/225608-worldedit#t1:other-downloads

Could you suggest a version I should be using for WE and WE_forge, so I could test with those versions and send you the server log if I still run into problems? Thank you.

**Comment by SBPrime** [comment]
Ad. 1. No problem, and your welcome.

Ad. 2. This might be a problem... WE 6.0 is no longer supported because of API changes. 

Currently you can do:
1. Try using WorldEdit 6.1.2+ (forge+bukkit) on cauldron. It might work, it might not no idea.
2. Try using WorldEdit 6.1.2+ bukkit only (without forge) you will lose some functionality but it might work
3. Download the latest version of WE and compile it against forge 1.7
4. Use older version of AWE (I think that the last version that supports WE 6.0 is 3.3.8)

I'll keep this open because there is always an option that I'll add support for WE 6.0 and WE 6.1.2+ in the latest version, but no promises.

**Comment by enarkay** [comment]
Okay thank you for all the kind and timely answers, they've been of great help!
I will test out your suggestions as soon as I find some time, and let you know about the results.

**Comment by enarkay** [comment]
I'm glad to report that I was able to find a snapshot version of WE_forge 6.1.2 for 1.7.10, and using 6.1.2 version of both WE and WE_forge along with AWE no longer produces errors or problems.

I would be completely okay to have the issue closed if you agree as well.
Thank you for your care and support for the issue:)

**Comment by SBPrime** [comment]
Great to hear.
